Repository robustmq/robustmq, pull requests merged in 2024-12, with the labels that each got.

#665 feat: Add metrics connack auth error
  src/mqtt-broker/src/observability/metrics/packets.rs
Labels: Size: S

#667 fix: Remove code that initializes the cache repeatedly
  src/placement-center/src/lib.rs
  src/placement-center/src/raft/raft_node.rs
Labels: size/xs

#668 fix: Delete raft v1 related GRPC code
  src/grpc-clients/src/placement/placement/call.rs
  src/grpc-clients/src/placement/placement/mod.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/route/apply.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/protocol/src/placement_center/proto/inner.proto
Labels: Size: M

#671 feat: Add metrics packets_connack_auth_error
  src/mqtt-broker/src/observability/metrics/packets.rs
Labels: Size: S

#669 fix: Delete the duplicate RaftNode struct
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/core/mod.rs
  src/placement-center/src/core/raft_node.rs
Labels: Size: S

#672 refactor: update code formatting and remove unused imports
  src/cmd/src/placement-center/server.rs
  src/placement-center/src/raft/network/network.rs
Labels: size/xs

#674 fix: correct node id range check
  src/placement-center/src/core/cluster.rs
Labels: size/xs

#673 feat: mqtt broker implements blacklist storage interface
  src/common/metadata-struct/src/acl/mqtt_blacklist.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/security/acl/metadata.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/security/mysql/mod.rs
  src/mqtt-broker/src/security/placement/mod.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/storage/blacklist.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  tests/tests/mqtt_protocol/acl_authorization_test.rs
Labels: Size: M

#681 feat: 622 mqtt command supports viewing a list of mqtt topics (No test yet!!)
  Cargo.lock
  Cargo.toml
  src/cli-command/src/mqtt.rs
  src/cmd/Cargo.toml
  src/cmd/src/cli-command/command.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
Labels: Size: M

#684 feat: add raft metrics endpoint- Implement new endpoint for Raft metrics
  src/placement-center/src/server/http/index.rs
  src/placement-center/src/server/http/server.rs
Labels: Size: S

#685 fix: Fixed bugs in mqtt protocol related functional test cases
  .github/workflows/mqtt-ig-test.yml
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/tcp/tcp_server.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/ping_test.rs
  tests/tests/mqtt_protocol/sub_options_test.rs
Labels: Size: M

#687 refactor: remove unused placement cluster metadata
  src/placement-center/src/core/cache.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/controller.rs
Labels: Size: M

#686 feat: support list sub scription framework
  src/cli-command/src/mqtt.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  tests/tests/mqtt_client/slow_sub_test.rs
Labels: Size: M

#690 test: Add pub/sub test cases for ws/wss.
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/pub_qos_test.rs
  tests/tests/mqtt_protocol/sub34_qos_test.rs
  tests/tests/mqtt_protocol/ws_sub_pub_test.rs
  tests/tests/mqtt_protocol/wss_sub_pub_test.rs
Labels: Size: M

#691 feat: journal client logic optimization
  src/cli-command/src/placement.rs
  src/grpc-clients/src/mqtt/inner/call.rs
  src/grpc-clients/src/mqtt/inner/mod.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/src/placement/inner/call.rs
  src/grpc-clients/src/placement/inner/mod.rs
  src/grpc-clients/src/placement/mod.rs
  src/grpc-clients/src/pool.rs
  src/grpc-clients/tests/placement/journal/segment.rs
  src/grpc-clients/tests/placement/journal/shard.rs
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs
  src/journal-client/src/error.rs
  src/journal-client/src/lib.rs
  src/journal-client/src/reader.rs
  src/journal-client/src/writer.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/cluster.rs
  src/mqtt-broker/src/handler/pkid.rs
  src/mqtt-broker/src/storage/cluster.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  src/storage-adapter/src/journal/mod.rs
  src/storage-adapter/src/journal/offset.rs
  tests/tests/journal_client/base_test.rs
  tests/tests/place_server/exclusive_sub_test.rs
  tests/tests/place_server/share_sub.rs
Labels: Size: M

#696 feat: add validation for get_share_sub_leader method
  .gitignore
  src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#698 feat: Optimize the journal client code
  src/journal-client/src/error.rs
  src/journal-client/src/reader.rs
  src/journal-client/src/writer.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/storage-adapter/src/journal/mod.rs
  src/storage-adapter/src/journal/offset.rs
  tests/tests/mqtt_protocol/share_sub_test.rs
Labels: Size: M

#700 feat: Journa Client code optimization
  src/journal-client/src/cache.rs
  src/journal-client/src/error.rs
  src/journal-client/src/lib.rs
  src/journal-client/src/reader.rs
  src/journal-client/src/writer.rs
Labels: Size: M

#702 feat: subscribe support queue mode
  .github/actions/build-linux-artifacts/action.yml
  .github/actions/build-macos-artifacts/action.yml
  .gitignore
  config/journal-server.toml
  config/mqtt-server.toml
  config/placement-center.toml
  docs/cn/系统架构/配置说明/mqtt-server.md
  docs/cn/系统架构/配置说明/placement-center.md
  example/mqtt-cluster/journal-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  example/mqtt-cluster/stop.sh
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_placement_center.rs
  src/common/base/src/config/placement_center.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  tests/tests/mqtt_protocol/share_sub_test.rs
  tests/tests/place_server/share_sub.rs
Labels: Size: M

#706 ci: ci support auto exit
  .github/workflows/journal-ig-test.yml
  .github/workflows/mqtt-ig-test.yml
  .github/workflows/place-ig-test.yml
  .github/workflows/unit-test.yml
  makefile
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
  scripts/unit-test.sh
Labels: Size: M

#704 feat: Journa Client code optimization
  src/common/metadata-struct/src/adapter/record.rs
  src/journal-client/src/async_reader.rs
  src/journal-client/src/async_writer.rs
  src/journal-client/src/client.rs
  src/journal-client/src/lib.rs
  src/journal-server/src/segment/read.rs
  src/mqtt-broker/src/subscribe/sub_exclusive.rs
  src/mqtt-broker/src/subscribe/sub_share_leader.rs
  src/protocol/src/journal_server/proto/engine.proto
  src/storage-adapter/src/journal/mod.rs
Labels: Size: M

#708 feat(placement-center): monitor leader transitions in raft
  src/placement-center/src/lib.rs
Labels: Size: S

#711 build: build vitepress for docs
  docs/.vitepress/config.mts
  docs/.vitepress/src/configs/en.mts
  docs/.vitepress/src/configs/zh.mts
  docs/.vitepress/src/docs.mts
  docs/.vitepress/src/head.mts
  docs/.vitepress/src/nav/en.mts
  docs/.vitepress/src/nav/zh.mts
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/.vitepress/src/theme.mts
  docs/en/ Introduction/What-is-RobustMQ.md
  docs/en/Getting-Started/Overview.md
  docs/en/RobustMQ-MQTT/mqtt-feature.md
  docs/en/index.md
  docs/images/logo-large.jpg
  docs/images/logo.png
  docs/index.md
  docs/zh/Architect/Broker-Server.md
  docs/zh/Architect/Configuration/Mqtt-Server.md
  docs/zh/Architect/Configuration/Placement-Center.md
  docs/zh/Architect/Journal-Server.md
  docs/zh/Architect/OverView.md
  docs/zh/Architect/Placement-Center.md
  docs/zh/Architect/Storage-Adapter.md
  docs/zh/Architect/Terminology.md
  docs/zh/Architect/Test-Case.md
  docs/zh/ContributionGuide/Build-Develop-Env.md
  docs/zh/ContributionGuide/Cargo-Running.md
  docs/zh/ContributionGuide/Code-Structure.md
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
  docs/zh/ContributionGuide/VsCode-Running.md
  docs/zh/OtherData/RobustMQ-Rust-China-For-2024.md
  docs/zh/OverView/RoadMap-For-2024.md
  docs/zh/OverView/What-is-RobustMQ.md
  docs/zh/OverView/Why-RobustMQ.md
  docs/zh/QuickGuide/Overview.md
  docs/zh/QuickGuide/Run-Cluster-Mode.md
  docs/zh/QuickGuide/Run-Standalone-Mode.md
  docs/zh/RobustMQ-MQTT/Overview.md
  docs/zh/VersionRecord/0.1.0-beta.md
  package-lock.json
  package.json
Labels: Size: XL

#715 build: build vitepress for robustmq
  .github/workflows/deployment-vite.yml
  docs/.vitepress/config.mts
  docs/.vitepress/src/theme.mts
  docs/en/index.md
  docs/index.md
Labels: Size: S

#712 fix: Resolve multi-threading issue with column families in RocksDB
  Cargo.lock
  Cargo.toml
  src/common/rocksdb-engine/Cargo.toml
  src/common/rocksdb-engine/src/lib.rs
  src/journal-server/src/index/offset.rs
  src/journal-server/src/index/tag.rs
  src/journal-server/src/index/time.rs
  src/placement-center/src/mqtt/controller/message_expire.rs
  src/placement-center/src/mqtt/controller/mod.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  src/placement-center/src/raft/store/log_store.rs
  src/placement-center/src/raft/store/state_machine_store.rs
  src/placement-center/src/route/mod.rs
  tests/tests/mqtt_server/topic_storage_test.rs
Labels: Size: M

#717 docs: Quick guide doc
  docs/zh/ContributionGuide/Github-Pull-Request-Example.md
Labels: Size: M

#716 test: Add the Journal Engine test case
  example/mqtt-cluster/placement-center/node-1.toml
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
  src/journal-server/src/index/time.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/write.rs
  tests/tests/mqtt_protocol/sub_identifier_test.rs
Labels: Size: M

#723 ci: fix a error about multiple line command
  docs/images/WechatGroup.png
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
Labels: Size: S

#718 test: Add the Journal Engine test case
  src/grpc-clients/src/utils.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/mod.rs
  src/journal-server/src/core/test.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/keys.rs
  src/journal-server/src/index/offset.rs
  src/journal-server/src/index/tag.rs
  src/journal-server/src/index/time.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/write.rs
  src/protocol/src/journal_server/proto/record.proto
Labels: Size: XL

#725 test: Add the Journal Engine test case
  src/journal-server/src/core/test.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/keys.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/write.rs
  src/mqtt-broker/src/handler/heartbreat.rs
Labels: Size: M

#726 test: Add the Journal Engine test case
  docs/zh/OverView/RoadMap-For-2024.md
  docs/zh/OverView/RoadMap.md
  docs/zh/VersionRecord/Summary-2024.md
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/core/cluster_config.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/mod.rs
  src/journal-server/src/core/notification.rs
  src/journal-server/src/core/offset.rs
  src/journal-server/src/core/record.rs
  src/journal-server/src/core/segment.rs
  src/journal-server/src/core/segment_status.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/core/test.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/scroll.rs
  src/journal-server/src/segment/write.rs
  src/journal-server/src/server/grpc/inner.rs
  src/journal-server/src/server/grpc/server.rs
  src/journal-server/src/server/tcp/server.rs
  src/placement-center/src/core/cache.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/mqtt/controller/message_expire.rs
  src/placement-center/src/mqtt/controller/mod.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/server/grpc/service_journal.rs
Labels: Size: XL

#727 fix: Optimizing Code Warnings
  src/journal-server/src/lib.rs
Labels: size/xs

#728 feat: add metrics packets.connack.error
  src/mqtt-broker/src/observability/metrics/packets.rs
Labels: Size: S
