Repository robustmq/robustmq, pull requests merged in 2024-11, with the labels that each got.

#587 feat: Journal Client read and write data flow test cases
  Cargo.lock
  src/common/metadata-struct/src/journal/node_extend.rs
  src/journal-client/Cargo.toml
  src/journal-client/src/lib.rs
  src/journal-client/src/tool.rs
  src/journal-client/tests/base_test.rs
  src/journal-client/tests/data_test.rs
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/handler/cluster.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/mod.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/write.rs
  src/journal-server/src/server/connection_manager.rs
  src/journal-server/src/server/tcp/server.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
Labels: Size: L

#588 test: a test case for is_message_expire
  src/journal-server/src/segment/read.rs
  src/mqtt-broker/src/handler/message.rs
Labels: Size: S

#589 test: Fix integration test errors
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/start.sh
  example/mqtt-cluster/stop.sh
  src/common/metadata-struct/src/journal/node_extend.rs
  src/grpc-clients/tests/openraft_test.rs
  src/journal-client/tests/base_test.rs
  src/journal-client/tests/data_test.rs
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/handler/cluster.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/server/grpc/inner.rs
  src/placement-center/src/core/journal/segmet.rs
  src/placement-center/src/route/journal.rs
Labels: Size: M

#593 docs: update a new picture for WechatGroup.jpg
  README.md
  docs/images/WechatGroup.jpg
  docs/images/WechatGroup.png
Labels: size/xs

#592 refactor: Add validation to the set_idempotent_data method in cementService and fill in the test case
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/validate.rs
  src/placement-center/tests/common.rs
  src/placement-center/tests/grpc_clients_test.rs
Labels: Size: S

#595 feat: Journal Engine related logic development
  makefile
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/journal/shard.rs
  src/grpc-clients/src/journal/inner/call.rs
  src/grpc-clients/src/journal/inner/mod.rs
  src/grpc-clients/src/journal/mod.rs
  src/journal-client/tests/base_test.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/mod.rs
  src/journal-server/src/core/segment.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/fold.rs
  src/journal-server/src/segment/mod.rs
  src/journal-server/src/server/grpc/inner.rs
  src/placement-center/src/controller/journal/controller.rs
  src/placement-center/src/controller/journal/mod.rs
  src/placement-center/src/controller/placement/mod.rs
  src/placement-center/src/core/cache.rs
  src/placement-center/src/core/controller.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/core/journal/segmet.rs
  src/placement-center/src/core/journal/shard.rs
  src/placement-center/src/core/mod.rs
  src/placement-center/src/journal/cache.rs
  src/placement-center/src/journal/controller/call_node.rs
  src/placement-center/src/journal/controller/gc.rs
  src/placement-center/src/journal/controller/mod.rs
  src/placement-center/src/journal/controller/preferred_election.rs
  src/placement-center/src/journal/mod.rs
  src/placement-center/src/journal/services/mod.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  src/placement-center/src/mqtt/controller/message_expire.rs
  src/placement-center/src/mqtt/controller/mod.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  src/placement-center/src/mqtt/mod.rs
  src/placement-center/src/mqtt/services/mod.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/raft/raftv1/machine.rs
  src/placement-center/src/route/cluster.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/journal.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/http/server.rs
  src/placement-center/src/storage/journal/segment.rs
  src/protocol/src/journal_server/proto/inner.proto
Labels: Size: XL

#597 feat: Journal Engine logic is complete
  Cargo.lock
  Cargo.toml
  makefile
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/journal/shard.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/segment.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/index/mod.rs
  src/journal-server/src/segment/write.rs
  src/placement-center/src/journal/controller/call_node.rs
  src/placement-center/src/journal/controller/gc.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/route/journal.rs
Labels: Size: L

#594 refactor: update cache when operating user; add test case for user permissions.
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/permission34_test.rs
  src/mqtt-broker/tests/permission5_test.rs
Labels: Size: L

#599 refactor: support for creating and deleting user from multiple information sources
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/security/mysql/mod.rs
  src/mqtt-broker/src/security/placement/mod.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
Labels: Size: M

#601 feat: Add Auth packet(15)
  src/protocol/src/mqtt/codec.rs
  src/protocol/src/mqtt/common.rs
  src/protocol/src/mqtt/mqttv4/codec.rs
  src/protocol/src/mqtt/mqttv5/auth.rs
  src/protocol/src/mqtt/mqttv5/codec.rs
  src/protocol/src/mqtt/mqttv5/mod.rs
Labels: Size: M

#600 test: test Free Disk Space
  .github/workflows/free-disk-space.yml
  scripts/integration-testing.sh
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/placement/cluster.rs
  src/journal-server/src/index/message_key.rs
  src/journal-server/src/index/mod.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/route/cluster.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/server/grpc/service_placement.rs
Labels: Size: M

#604 feat: journal code logic optimization
  Cargo.toml
  bin/robust-server
  codecheck.sh
  makefile
  scripts/build-release.sh
  scripts/integration-testing.sh
  src/common/metadata-struct/src/journal/mod.rs
  src/common/metadata-struct/src/journal/segment_meta.rs
  src/journal-client/tests/base_test.rs
  src/journal-client/tests/data_test.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/mod.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/shard.rs
  src/placement-center/src/journal/cache.rs
  src/placement-center/src/journal/controller/gc.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/journal.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/placement-center/src/storage/journal/mod.rs
  src/placement-center/src/storage/journal/segment_meta.rs
  src/placement-center/src/storage/keys.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
  src/protocol/src/placement_center/proto/journal.proto
Labels: Size: L

#605 refactor: Add validation to the register_node method in GrpcPlacementService and fill in the test case
  src/common/base/src/error/common.rs
  src/placement-center/src/server/grpc/validate.rs
  src/placement-center/tests/broker_heartbeat_test.rs
  src/placement-center/tests/cluster_node_test.rs
  src/placement-center/tests/grpc_clients_test.rs
Labels: Size: M

#609 ci: Implement caching for CI/CD builds using sccache.
  .github/actions/setup-builder/action.yaml
  .github/actions/setup-rust-runtime/action.yml
  .github/workflows/rust-testing.yml
Labels: Size: M

#611 feat: Write flow optimization
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/write.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/mod.rs
  src/journal-server/src/segment/write.rs
  src/journal-server/src/server/tcp/server.rs
Labels: Size: M

#612 feat: Segment state machine transition development
  src/common/metadata-struct/src/journal/segment.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/write.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/mod.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/status.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/route/data.rs
Labels: Size: M

#615 feat: Segment state machine development
  src/common/metadata-struct/src/journal/segment.rs
  src/grpc-clients/tests/placement/segment.rs
  src/journal-server/src/core/write.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/mod.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/placement-center/tests/grpc_clients_test.rs
  src/protocol/src/placement_center/proto/journal.proto
Labels: Size: M

#616 test: Split integration tests and unit tests
  .github/workflows/code-style.yml
  .github/workflows/devskim-analysis.yml
  .github/workflows/release-raft.yaml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  Cargo.lock
  Cargo.toml
  makefile
  scripts/integration-test.sh
  scripts/unit-test.sh
  src/common/metadata-struct/src/journal/segment.rs
  src/journal-server/src/handler/shard.rs
  src/mqtt-broker/tests/mod.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/protocol/src/placement_center/proto/journal.proto
  tests/Cargo.toml
  tests/lib.rs
  tests/src/lib.rs
  tests/tests/journal_client/base_test.rs
  tests/tests/journal_client/data_test.rs
  tests/tests/journal_client/mod.rs
  tests/tests/journal_client/shard.rs
  tests/tests/mod.rs
  tests/tests/mqtt_client/mod.rs
  tests/tests/mqtt_client/mqtt/common.rs
  tests/tests/mqtt_client/mqtt/connect34_test.rs
  tests/tests/mqtt_client/mqtt/connect5_test.rs
  tests/tests/mqtt_client/mqtt/connect_packet_size_test.rs
  tests/tests/mqtt_client/mqtt/keep_alive_test.rs
  tests/tests/mqtt_client/mqtt/lastwill_message_test.rs
  tests/tests/mqtt_client/mqtt/mod.rs
  tests/tests/mqtt_client/mqtt/permission34_test.rs
  tests/tests/mqtt_client/mqtt/permission5_test.rs
  tests/tests/mqtt_client/mqtt/ping_test.rs
  tests/tests/mqtt_client/mqtt/pub_qos_test.rs
  tests/tests/mqtt_client/mqtt/req_resp_test.rs
  tests/tests/mqtt_client/mqtt/retain_message_test.rs
  tests/tests/mqtt_client/mqtt/share_sub_test.rs
  tests/tests/mqtt_client/mqtt/sub34_qos_test.rs
  tests/tests/mqtt_client/mqtt/sub5_qos_test.rs
  tests/tests/mqtt_client/mqtt/sub_identifier_test.rs
  tests/tests/mqtt_client/mqtt/sub_options_test.rs
  tests/tests/mqtt_client/mqtt/topic_alias_test.rs
  tests/tests/mqtt_client/mqtt/user_properties_test.rs
  tests/tests/mqtt_client/storage/mod.rs
Labels: Size: XL

#617 refactor: MQTT Broker adds threads to periodically synchronize User and Acl information
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/user.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/mod.rs
Labels: Size: S

#621 test: Test case completion of journal module in placement
  makefile
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/journal/cache.rs
  src/placement-center/src/journal/controller/call_node.rs
  src/placement-center/src/journal/controller/gc.rs
  src/placement-center/src/journal/services/segmet.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  src/placement-center/src/mqtt/mod.rs
  src/placement-center/src/route/apply.rs
Labels: Size: M

#627 ci: Integrate CI with pre-commit checks.
  .github/actions/setup-builder/action.yaml
  .github/workflows/code-style.yml
  .github/workflows/license.yaml
  .github/workflows/place-ig-test.yml
  .github/workflows/unit-test.yml
  .gitignore
  deny.toml
  scripts/unit-test.sh
Labels: Size: M

#628 docs: update readme
  README.md
Labels: size/xs

#631 docs: Update CN README and docs
  README.md
  docs/cn/系统架构/测试用例.md
  makefile
Labels: Size: S

#634 refactor: #542 add validation to the get resource config method in grpc placement service
  scripts/unit-test.sh
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#637 refactor: Optimize the MQTT Connection structure
  Cargo.lock
  config/log4rs.yaml
  src/common/metadata-struct/Cargo.toml
  src/common/metadata-struct/src/mqtt/connection.rs
  src/common/metadata-struct/src/mqtt/mod.rs
  src/journal-server/src/segment/scroll.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/response.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/observability/system_topic/event.rs
  src/mqtt-broker/src/security/acl/mod.rs
  src/mqtt-broker/src/security/mod.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
Labels: Size: M

#640 refactor: Read data according to Offset/Timestamp/Tag/Key
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/segment_meta.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/keys.rs
  src/journal-server/src/index/mod.rs
  src/journal-server/src/index/offset.rs
  src/journal-server/src/index/tag.rs
  src/journal-server/src/index/time.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/write.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/protocol/src/journal_server/proto/engine.proto
  tests/tests/journal_client/base_test.rs
  tests/tests/journal_client/data_test.rs
Labels: Size: L

#645 fix: update excluded typo
  _typos.toml
  src/mqtt-broker/src/observability/metrics/packets.rs
Labels: Size: M

#643 feat: MQTT Command supports viewing connection information
  src/cli-command/src/mqtt.rs
  src/cmd/Cargo.toml
  src/cmd/src/cli-command/command.rs
  src/common/base/src/tools.rs
  src/common/metadata-struct/src/mqtt/connection.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/inner.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/src/pool.rs
  src/grpc-clients/tests/mqtt/mod.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/mqtt/mqtt_connect_test.rs
  src/journal-server/src/handler/data.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/connection.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
Labels: Size: M

#651 refactor: 635 test optimize integration tests in the storage directory in mqtt broker
  src/mqtt-broker/src/storage/cluster.rs
  src/mqtt-broker/src/storage/session.rs
  src/mqtt-broker/src/storage/user.rs
  tests/tests/mqtt_server/storage/cluster_storage_test.rs
  tests/tests/mqtt_server/storage/mod.rs
  tests/tests/mqtt_server/storage/session_storage_test.rs
  tests/tests/mqtt_server/storage/user_storage_test.rs
Labels: Size: M

#654 style: 去除无效前缀
  src/placement-center/src/lib.rs
Labels: size/xs

#652 feat: implements acl related funtions
  Cargo.lock
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/metadata-struct/src/acl/mqtt_acl.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/src/placement/mqtt/call.rs
  src/grpc-clients/src/placement/mqtt/mod.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_acl_test.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/acl.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/acl/metadata.rs
  src/mqtt-broker/src/security/acl/mod.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/security/mysql/mod.rs
  src/mqtt-broker/src/security/mysql/sql.sql
  src/mqtt-broker/src/security/placement/mod.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/storage/acl.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/placement-center/src/storage/mqtt/acl.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  src/protocol/src/placement_center/proto/mqtt.proto
  tests/tests/mqtt_client/mqtt/acl_authorization_test.rs
  tests/tests/mqtt_client/mqtt/common.rs
  tests/tests/mqtt_client/mqtt/mod.rs
Labels: Size: XL

#653 feat: Journal Engine Client send data flow optimization
  README.md
  src/cli-command/src/lib.rs
  src/grpc-clients/src/lib.rs
  src/journal-client/src/cache.rs
  src/journal-client/src/connection.rs
  src/journal-client/src/error.rs
  src/journal-client/src/group.rs
  src/journal-client/src/lib.rs
  src/journal-client/src/option.rs
  src/journal-client/src/reader.rs
  src/journal-client/src/sender.rs
  src/journal-client/src/service.rs
  src/journal-client/src/writer.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/offset.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/write.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/observability/metrics/packets.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
  src/protocol/src/journal_server/proto/record.proto
  tests/tests/journal_client/base_test.rs
  tests/tests/journal_client/data_test.rs
Labels: Size: XL

#660 feat: add metrics_packets_sent
  src/mqtt-broker/src/observability/metrics/packets.rs
Labels: Size: M

#658 refactor: Remove the raft v1 code
  src/placement-center/src/core/cache.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/raft/error.rs
  src/placement-center/src/raft/mod.rs
  src/placement-center/src/raft/network/connection.rs
  src/placement-center/src/raft/network/mod.rs
  src/placement-center/src/raft/network/network.rs
  src/placement-center/src/raft/raft_node.rs
  src/placement-center/src/raft/raftv1/machine.rs
  src/placement-center/src/raft/raftv1/mod.rs
  src/placement-center/src/raft/raftv1/peer.rs
  src/placement-center/src/raft/raftv1/rocksdb.rs
  src/placement-center/src/raft/raftv1/snapshot.rs
  src/placement-center/src/raft/raftv1/storage.rs
  src/placement-center/src/raft/raftv2/mod.rs
  src/placement-center/src/raft/route/mod.rs
  src/placement-center/src/raft/store/log_store.rs
  src/placement-center/src/raft/store/mod.rs
  src/placement-center/src/raft/store/state_machine_store.rs
  src/placement-center/src/raft/typeconfig.rs
  src/placement-center/src/route/apply.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/server/grpc/services_openraft.rs
  src/placement-center/src/server/http/server.rs
  src/placement-center/src/storage/keys.rs
Labels: Size: XL
