Repository robustmq/robustmq, pull requests merged in 2024-10, with the labels that each got.

#479 MINOR: Add comments to placement_center's common.proto
  src/protocol/src/broker_server/generate/admin.rs
  src/protocol/src/broker_server/generate/placement.rs
  src/protocol/src/journal_server/generate/protocol/fetch.rs
  src/protocol/src/journal_server/generate/protocol/header.rs
  src/protocol/src/journal_server/generate/protocol/produce.rs
  src/protocol/src/journal_server/generate/record/record.rs
  src/protocol/src/placement_center/generate/common.rs
  src/protocol/src/placement_center/generate/journal.rs
  src/protocol/src/placement_center/generate/kv.rs
  src/protocol/src/placement_center/generate/mqtt.rs
  src/protocol/src/placement_center/generate/placement.rs
  src/protocol/src/placement_center/proto/common.proto
Labels: Size: M

#480 test: test pr
  config/log4rs.yaml
  src/placement-center/src/raftv1/rocksdb.rs
  src/placement-center/src/server/http/raft.rs
  src/placement-center/src/storage/route/cluster.rs
  src/placement-center/src/storage/route/data.rs
Labels: Size: S

#481 refactor: Optimize the rocksdb code
  Cargo.lock
  Cargo.toml
  scripts/build-release.sh
  src/cli-command/src/placement.rs
  src/common/raft-rocksdb/Cargo.toml
  src/common/raft-rocksdb/src/lib.rs
  src/common/raft-rocksdb/tests/test.rs
  src/common/rocksdb-engine/src/lib.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/raftv1/rocksdb.rs
  src/placement-center/src/raftv1/snapshot.rs
  src/placement-center/src/raftv2/error.rs
  src/placement-center/src/raftv2/network/connection.rs
  src/placement-center/src/raftv2/network/network.rs
  src/placement-center/src/raftv2/raft_node.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/storage/engine.rs
  src/protocol/src/broker_server/generate/admin.rs
  src/protocol/src/placement_center/generate/placement.rs
  src/protocol/src/placement_center/proto/placement.proto
  src/storage-adapter/src/local_rocksdb/mod.rs
Labels: Size: L

#482 refactor: Placement Center Raft snapshot module optimization
  Cargo.toml
  config/example/cluster/placement-center/node-1.toml
  config/example/cluster/placement-center/node-3.toml
  config/example/cluster/storage-engine/node-1.toml
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  example/mqtt-cluster/start.sh
  nohup.out
  scripts/build-release.sh
  src/placement-center/src/lib.rs
  src/placement-center/src/raftv2/store/state_machine_store.rs
  src/placement-center/src/server/grpc/mod.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/services_raftv2.rs
  src/placement-center/src/storage/route/mod.rs
Labels: Size: L

#483 MINOR: Add comments to storage/placement/cluster.rs
  src/placement-center/src/storage/placement/cluster.rs
Labels: Size: S

#484 refactor: Placement Center Raft snapshot module optimization
  Cargo.lock
  README.md
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  example/mqtt-cluster/start.sh
  example/mqtt-cluster/stop.sh
  nohup.out
  scripts/integration-testing.sh
  src/clients/Cargo.toml
  src/clients/src/placement/mod.rs
  src/clients/src/poll.rs
  src/protocol/src/broker_server/generate/admin.rs
  src/protocol/src/broker_server/generate/placement.rs
  src/protocol/src/journal_server/generate/protocol/fetch.rs
  src/protocol/src/journal_server/generate/protocol/header.rs
  src/protocol/src/journal_server/generate/protocol/produce.rs
  src/protocol/src/journal_server/generate/record/record.rs
  src/protocol/src/placement_center/generate/common.rs
  src/protocol/src/placement_center/generate/journal.rs
  src/protocol/src/placement_center/generate/kv.rs
  src/protocol/src/placement_center/generate/mqtt.rs
  src/protocol/src/placement_center/generate/placement.rs
  tests/config/journal-server.toml
  tests/config/mqtt-server-1.toml
  tests/config/mqtt-server-2.toml
  tests/config/placement-center.toml
Labels: Size: XL

#488 docs: Fix typos in documentation
  README.md
  docs/cn/系统架构/概览.md
Labels: size/xs

#492 feat: Optimize the function of client
  src/clients/src/placement/journal/inner.rs
  src/clients/src/placement/journal/mod.rs
  src/clients/src/placement/kv/inner.rs
  src/clients/src/placement/kv/mod.rs
  src/clients/src/placement/mod.rs
  src/clients/src/placement/mqtt/inner.rs
  src/clients/src/placement/mqtt/mod.rs
  src/clients/src/placement/openraft/inner.rs
  src/clients/src/placement/openraft/mod.rs
  src/clients/src/placement/placement/inner.rs
  src/clients/src/placement/placement/mod.rs
  src/clients/src/poll.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/protocol/src/broker_server/generate/admin.rs
  src/protocol/src/placement_center/generate/mqtt.rs
  src/protocol/src/placement_center/proto/mqtt.proto
Labels: Size: XL

#493 test: Add test cases to is_has_to_forward method
  src/clients/src/placement/mod.rs
Labels: Size: S

#494 test: MQTT Broker supplements the Keep Alive test case
  .gitignore
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/server/connection.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/mqtt-broker/tests/keep_alive_test.rs
  src/placement-center/src/controller/mqtt/call_broker.rs
Labels: Size: M

#499 refactor: Optimize the placement center section
  src/mqtt-broker/tests/sub_options_test.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/server/grpc/mod.rs
  src/placement-center/src/server/grpc/services_openraft.rs
  src/placement-center/src/server/http/index.rs
  src/placement-center/src/server/http/journal/mod.rs
  src/placement-center/src/server/http/mod.rs
  src/placement-center/src/server/http/mqtt/cluster.rs
  src/placement-center/src/server/http/mqtt/mod.rs
  src/placement-center/src/server/http/mqtt/user.rs
  src/placement-center/src/server/http/raft.rs
  src/placement-center/src/server/http/server.rs
Labels: Size: M

#503 test: Add validation to the Set method in the GrpcKvService file
  src/clients/tests/kv_test.rs
Labels: Size: S

#511 fix: Add &BrokerMQTTConfig param to register_node and unregister_node functions and refine the cluster_node_test test case
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/storage/cluster.rs
Labels: Size: S

#517 test: add test case to the cluster_status and register_node interfaces of GrpcPlacementService
  src/grpc-clients/tests/placement_test.rs
  src/placement-center/src/server/grpc/service_placement.rs
Labels: Size: M

#520 feat:Journal Engine KV storage layer development
  Cargo.lock
  src/common/base/src/error/common.rs
  src/common/base/src/error/journal_server.rs
  src/common/metadata-struct/src/journal/group.rs
  src/common/metadata-struct/src/journal/mod.rs
  src/common/metadata-struct/src/journal/namespace.rs
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/journal/shard.rs
  src/journal-server/Cargo.toml
  src/journal-server/src/core/handler.rs
  src/journal-server/src/core/mod.rs
  src/journal-server/src/core/record.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/handler/mod.rs
  src/journal-server/src/kv/engine.rs
  src/journal-server/src/kv/mod.rs
  src/journal-server/src/kv/offset.rs
  src/journal-server/src/kv/rocksdb.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/metadata/shard.rs
  src/journal-server/src/record/record.rs
  src/journal-server/src/record/record_batch.rs
  src/placement-center/src/controller/mqtt/call_broker.rs
  src/storage-adapter/src/placement/mod.rs
Labels: Size: M

#530 fix: Fix code warnings and remove invalid code
  .github/workflows/rust-testing.yml
  src/cmd/src/cli-command/mqtt-server/command.rs
  src/cmd/src/cli-command/placement-center/command.rs
  src/cmd/src/journal-server/server.rs
  src/cmd/src/mqtt-server/server.rs
  src/cmd/src/placement-center/server.rs
  src/grpc-clients/src/mqtt/placement/call.rs
  src/grpc-clients/src/mqtt/placement/inner.rs
  src/journal-server/src/lib.rs
  src/mqtt-broker/src/server/grpc/placement.rs
  src/protocol/src/broker_mqtt/proto/placement.proto
  src/protocol/src/journal_server/proto/record/mod.rs
  src/protocol/src/placement_center/proto/common.proto
  src/protocol/tests/protobuf.rs
Labels: Size: M

#526 refactor: Define a trait for parameter validation and implement it for RegisterNodeRequest.
  Cargo.lock
  Cargo.toml
  src/grpc-clients/Cargo.toml
  src/placement-center/src/server/grpc/mod.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/validate.rs
  src/protocol/Cargo.toml
Labels: Size: S

#531 feat: Journal Engine component initialization development
  docs/images/WechatGroup.png
  src/common/base/src/error/journal_server.rs
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/placement/mod.rs
  src/common/metadata-struct/src/placement/node.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/command.rs
  src/journal-server/src/core/handler.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/server/tcp/server.rs
  src/mqtt-broker/src/storage/cluster.rs
  src/placement-center/src/cache/placement.rs
  src/placement-center/src/core/share_sub.rs
  src/placement-center/src/storage/placement/node.rs
  src/placement-center/src/storage/route/cluster.rs
  src/placement-center/tests/broker_heartbeat_test.rs
  src/placement-center/tests/cluster_node_test.rs
  src/protocol/build.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
Labels: Size: M

#532 fix: Remove redundant comments
  src/protocol/src/lib.rs
  src/protocol/src/mqtt/common.rs
  src/protocol/src/mqtt/mqttv4/connack.rs
  src/protocol/src/mqtt/mqttv4/connect.rs
  src/protocol/src/mqtt/mqttv4/disconnect.rs
  src/protocol/src/mqtt/mqttv4/mod.rs
  src/protocol/src/mqtt/mqttv4/ping.rs
  src/protocol/src/mqtt/mqttv4/puback.rs
  src/protocol/src/mqtt/mqttv4/pubcomp.rs
  src/protocol/src/mqtt/mqttv4/publish.rs
  src/protocol/src/mqtt/mqttv4/pubrec.rs
  src/protocol/src/mqtt/mqttv4/pubrel.rs
  src/protocol/src/mqtt/mqttv4/suback.rs
  src/protocol/src/mqtt/mqttv4/subscribe.rs
  src/protocol/src/mqtt/mqttv4/unsuback.rs
  src/protocol/src/mqtt/mqttv4/unsubscribe.rs
  src/protocol/src/mqtt/mqttv5/connack.rs
  src/protocol/src/mqtt/mqttv5/connect.rs
  src/protocol/src/mqtt/mqttv5/disconnect.rs
  src/protocol/src/mqtt/mqttv5/mod.rs
  src/protocol/src/mqtt/mqttv5/ping.rs
  src/protocol/src/mqtt/mqttv5/puback.rs
  src/protocol/src/mqtt/mqttv5/pubcomp.rs
  src/protocol/src/mqtt/mqttv5/publish.rs
  src/protocol/src/mqtt/mqttv5/pubrec.rs
  src/protocol/src/mqtt/mqttv5/pubrel.rs
  src/protocol/src/mqtt/mqttv5/suback.rs
  src/protocol/src/mqtt/mqttv5/subscribe.rs
  src/protocol/src/mqtt/mqttv5/unsuback.rs
  src/protocol/src/mqtt/mqttv5/unsubscribe.rs
Labels: Size: M

#533 chore: renamed Tcps to Tls
  src/journal-server/src/server/connection.rs
  src/journal-server/src/server/connection_manager.rs
  src/journal-server/src/server/tcp/server.rs
  src/journal-server/src/server/tcp/tls_server.rs
  src/mqtt-broker/src/server/connection.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/server/tcp/tls_server.rs
  src/protocol/src/mqtt/mqttv4/connect.rs
  src/protocol/tests/mqtt_frame.rs
Labels: Size: S

#534 ci: add a default value to JournalServerConfig and complement the journal_server_toml_test test case
  config/journal-server.toml
  src/common/base/src/config/default_journal_server.rs
  src/common/base/src/config/journal_server.rs
Labels: Size: M

#548 refactor: add validation to the un_register_node method in GrpcPlacementService and fill in the test case
  src/grpc-clients/tests/placement_test.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#551 feat: Optimize command-line tools
  Cargo.lock
  bin/robust-ctl
  bin/robustctl-mqtt
  src/cmd/Cargo.toml
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt-server/command.rs
  src/cmd/src/cli-command/placement-center/command.rs
Labels: Size: M

#552 refactor: Placement Center adds implementation of add_learner and change_membership GRPC
  src/grpc-clients/src/placement/mod.rs
  src/grpc-clients/src/placement/openraft/call.rs
  src/grpc-clients/src/placement/openraft/mod.rs
  src/grpc-clients/tests/openraft_test.rs
  src/placement-center/src/server/grpc/services_openraft.rs
  src/placement-center/src/server/http/mod.rs
  src/placement-center/src/server/http/raft.rs
  src/placement-center/src/server/http/server.rs
  src/protocol/src/placement_center/proto/openraft.proto
Labels: Size: M

#564 feat: MQTT Broker supplements the Subscription Options test case and fix a bug
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/tests/sub_options_test.rs
Labels: Size: M

#565 test: Add validation to the set_resource_config method in GrpcPlacementService and fill in the test case
  src/grpc-clients/tests/placement_test.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#566 feat: Placement Center completes the Shard/Segment logic
  Cargo.lock
  Cargo.toml
  example/mqtt-cluster/start.sh
  scripts/integration-testing.sh
  src/common/metadata-struct/src/journal/segment.rs
  src/journal-server/src/core/handler.rs
  src/mqtt-broker/tests/sub_options_test.rs
  src/placement-center/Cargo.toml
  src/placement-center/src/cache/journal.rs
  src/placement-center/src/cache/placement.rs
  src/placement-center/src/controller/journal/call_node.rs
  src/placement-center/src/controller/journal/mod.rs
  src/placement-center/src/controller/journal/segment_replica.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/journal/mod.rs
  src/placement-center/src/core/journal/segmet.rs
  src/placement-center/src/raftv1/machine.rs
  src/placement-center/src/server/grpc/service_journal.rs
  src/placement-center/src/storage/journal/segment.rs
  src/placement-center/src/storage/route/journal.rs
  src/placement-center/src/storage/route/kv.rs
  src/placement-center/src/storage/route/mod.rs
  src/placement-center/tests/grpc_clients_test.rs
  src/protocol/src/journal_server/proto/engine.proto
  src/protocol/src/placement_center/proto/journal.proto
Labels: Size: L

#572 refactor: MQTT Broker supports CreateUser, DeleteUser, ListUser GRPC Admin interfaces
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/inner.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/tests/common.rs
  src/grpc-clients/tests/mqtt/mod.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/openraft_test.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
Labels: Size: M

#577 chore: Rename types to comply with the rust naming convention
  src/cmd/src/cli-command/command.rs
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/journal_server.rs
  src/common/base/src/error/common.rs
  src/common/base/src/error/mqtt_broker.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/src/mqtt/placement/call.rs
  src/grpc-clients/src/mqtt/placement/mod.rs
  src/grpc-clients/tests/common.rs
  src/journal-client/tests/base.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/flow_control.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/response.rs
  src/mqtt-broker/src/handler/session.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/observability/metrics/packets.rs
  src/mqtt-broker/src/observability/system_topic/event.rs
  src/mqtt-broker/src/security/login/mod.rs
  src/mqtt-broker/src/security/login/plaintext.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/server/connection.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/packet.rs
  src/mqtt-broker/src/server/tcp/handler.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/storage/cluster.rs
  src/mqtt-broker/src/storage/topic.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/mqtt-broker/src/subscribe/sub_exclusive.rs
  src/mqtt-broker/src/subscribe/sub_share_follower.rs
  src/mqtt-broker/src/subscribe/sub_share_leader.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/mqtt-broker/src/subscribe/subscriber.rs
  src/mqtt-broker/tests/keep_alive_test.rs
  src/mqtt-broker/tests/sub_options_test.rs
  src/placement-center/src/core/journal/segmet.rs
  src/placement-center/src/route/cluster.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/route/mqtt.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/placement-center/src/storage/mqtt/lastwill.rs
  src/placement-center/src/storage/mqtt/topic.rs
  src/placement-center/tests/grpc_clients_test.rs
  src/protocol/src/mqtt/codec.rs
  src/protocol/src/mqtt/common.rs
  src/protocol/src/mqtt/mqttv4/codec.rs
  src/protocol/src/mqtt/mqttv5/codec.rs
  src/protocol/tests/mqtt_frame.rs
Labels: Size: XL

#579 feat: Add TLS support for gRPC servers
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/base/src/config/journal_server.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/server/grpc/server.rs
  src/journal-server/src/server/tcp/server.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/storage/cluster.rs
Labels: Size: S

#576 refactor: Improve the Journal Engine read and write related logic
  src/common/metadata-struct/src/journal/segment.rs
  src/grpc-clients/src/lib.rs
  src/journal-client/tests/base.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/data.rs
  src/journal-server/src/index/key_index.rs
  src/journal-server/src/index/mod.rs
  src/journal-server/src/index/offset_index.rs
  src/journal-server/src/index/tag_index.rs
  src/journal-server/src/index/time_index.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/mod.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/journal/segmet.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
Labels: Size: M

#580 fix: Revert "feat: Add TLS support for gRPC servers"
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/base/src/config/journal_server.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/server/grpc/server.rs
  src/journal-server/src/server/tcp/server.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/storage/cluster.rs
Labels: Size: S

#583 refactor: refactor code related to the command line
  Cargo.lock
  src/cli-command/src/mqtt.rs
  src/cli-command/src/placement.rs
  src/cmd/Cargo.toml
  src/cmd/src/cli-command/command.rs
Labels: Size: M
