Repository robustmq/robustmq, pull requests merged in 2024-09, with the labels that each got.

#434 docs: configuration documentation
  docs/cn/系统架构/配置说明/mqtt-server.md
  docs/cn/系统架构/配置说明/placement-center.md
Labels: Size: S

#441 Add English document
  docs/en/ Introduction/What is RobustMQ.md
Labels: Size: S

#437 feat: Compatible with Rocksdb
  Cargo.lock
  docs/cn/贡献指南/GitHub 贡献指南.md
  src/common/base/src/config/common.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/metadata-struct/src/adapter/record.rs
  src/common/rocksdb-engine/Cargo.toml
  src/common/rocksdb-engine/src/lib.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/tests/req_resp_test.rs
  src/placement-center/Cargo.toml
  src/placement-center/src/controller/mqtt/message_expire.rs
  src/placement-center/src/controller/mqtt/session_expire.rs
  src/placement-center/src/core/share_sub.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/raft/route/cluster.rs
  src/placement-center/src/storage/mqtt/lastwill.rs
  src/placement-center/src/storage/mqtt/session.rs
  src/placement-center/src/storage/mqtt/topic.rs
  src/placement-center/src/storage/mqtt/user.rs
  src/placement-center/src/storage/placement/raft.rs
  src/placement-center/src/storage/rocksdb.rs
  src/storage-adapter/Cargo.toml
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/local_rocksdb/mod.rs
  tests/config/mqtt-server-2.toml
Labels: Size: XL

#444 fix: warning message for unused code
  src/journal-server/src/record/header.rs
  src/journal-server/src/server/tcp/connection.rs
  src/journal-server/src/storage.rs
  src/mqtt-broker/src/observability/slow/qos.rs
  src/mqtt-broker/tests/share_sub_test.rs
  src/placement-center/src/core/share_sub.rs
  src/placement-center/src/raft/metadata.rs
  src/placement-center/src/server/http/server.rs
  src/placement-center/src/storage/journal/segment.rs
  src/protocol/tests/mqtt_frame.rs
Labels: Size: S

#445 feat: command-line tool supports' robustctl-mqtt status' to view broker node status
  Cargo.lock
  src/cli-command/Cargo.toml
  src/cli-command/src/lib.rs
  src/cli-command/src/mqtt.rs
  src/cli-command/src/placement.rs
  src/clients/src/mqtt/admin/call.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/placement-center/src/raft/machine.rs
  src/placement-center/src/raft/metadata.rs
Labels: Size: S

#448 feat: MQTT Broker and Placement Center cluster capability optimization
  src/clients/src/mqtt/mod.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/server/http/server.rs
  src/mqtt-broker/tests/common.rs
  src/placement-center/src/cache/placement.rs
  src/placement-center/src/raft/apply.rs
  src/placement-center/src/raft/route/cluster.rs
  src/placement-center/src/raft/route/mod.rs
  src/placement-center/src/server/grpc/service_placement.rs
  src/placement-center/src/storage/placement/cluster.rs
  src/placement-center/src/storage/placement/node.rs
  src/placement-center/tests/broker_heartbeat_test.rs
  src/placement-center/tests/grpc_clients_test.rs
  src/placement-center/tests/kv_storage_test.rs
  src/placement-center/tests/share_sub_test.rs
Labels: Size: M

#449 test: fix MQTT Broker supports test cases for Request/Response features
  rustfmt.toml
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/connect_test.rs
  src/mqtt-broker/tests/req_resp_test.rs
Labels: Size: M

#451 test: MQTT Broker supplements the Share Subscriptions test case
  src/mqtt-broker/tests/share_sub_test.rs
Labels: Size: S

#452 test: Add MQTT broker WebSocket connection test
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/connect_test.rs
Labels: Size: M

#455 refactor: Optimize packaging and startup scripts
  bin/robust-server
  config/log4rs.yaml
  makefile
  scripts/build-release.sh
  scripts/cross-package.sh
  src/placement-center/src/controller/mqtt/message_expire.rs
Labels: Size: M

#457 feat: sub dev
  scripts/build-release.sh
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/subscribe/sub_exclusive.rs
  src/mqtt-broker/src/subscribe/sub_share_leader.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/mqtt-broker/src/subscribe/subscriber.rs
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/connect_test.rs
Labels: Size: M

#459 fix: fix test cases
  scripts/integration-testing.sh
Labels: size/xs

#460 test: test pr
  .github/workflows/rust-testing.yml
  scripts/integration-testing.sh
  src/cli-command/src/lib.rs
Labels: size/xs

#461 test: test case
  src/cli-command/src/mqtt.rs
Labels: size/xs

#462 test: test test
  .github/workflows/rust-testing.yml
  src/cli-command/src/mqtt.rs
Labels: Size: S

#463 fix: Fixed connection pool bugs
  src/clients/src/mqtt/admin/inner.rs
  src/clients/src/mqtt/admin/mod.rs
  src/clients/src/mqtt/placement/inner.rs
  src/clients/src/mqtt/placement/mod.rs
  src/clients/src/placement/journal/inner.rs
  src/clients/src/placement/journal/mod.rs
  src/clients/src/placement/kv/inner.rs
  src/clients/src/placement/kv/mod.rs
  src/clients/src/placement/mqtt/inner.rs
  src/clients/src/placement/mqtt/mod.rs
  src/clients/src/placement/placement/inner.rs
  src/clients/src/placement/placement/mod.rs
  src/clients/src/poll.rs
  src/mqtt-broker/src/storage/topic.rs
  src/placement-center/src/raft/metadata.rs
Labels: Size: M

#464 fix: Fixed subscription bugs
  src/clients/src/poll.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/storage/topic.rs
  src/mqtt-broker/src/subscribe/sub_exclusive.rs
  src/mqtt-broker/src/subscribe/sub_share_leader.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/mqtt-broker/src/subscribe/subscriber.rs
  src/placement-center/tests/broker_heartbeat_test.rs
Labels: Size: M

#466 test: add subscribe identifier
  src/mqtt-broker/tests/sub_identifier.rs
Labels: Size: M

#469 feat: Placement center node receives a write request to be forwarded to the Leader node for processing
  src/clients/src/placement/mod.rs
  src/clients/src/placement/mqtt/call.rs
  src/clients/src/placement/mqtt/inner.rs
  src/clients/src/placement/mqtt/mod.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/protocol/src/placement_center/generate/mqtt.rs
  src/protocol/src/placement_center/proto/mqtt.proto
Labels: Size: L

#471 test: test
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/storage/topic.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/connect_packet_size_test.rs
  src/mqtt-broker/tests/sub5_qos_test.rs
  src/mqtt-broker/tests/sub_identifier_test.rs
  src/placement-center/src/raft/metadata.rs
  src/placement-center/tests/common.rs
  src/protocol/src/mqtt/common.rs
Labels: Size: M

#474 test: test test
  src/mqtt-broker/tests/common.rs
  src/mqtt-broker/tests/connect34_test.rs
  src/mqtt-broker/tests/connect5_test.rs
  src/mqtt-broker/tests/sub_identifier_test.rs
  tests/config/mqtt-server-1.toml
Labels: Size: S

#475 test: fix test bug
  rustfmt.toml
  src/clients/src/placement/mod.rs
  src/mqtt-broker/tests/sub_identifier_test.rs
  src/placement-center/src/raft/apply.rs
  src/placement-center/src/raft/route/cluster.rs
  src/placement-center/src/raft/route/mod.rs
  src/placement-center/src/server/grpc/service_placement.rs
Labels: Size: M
