Repository robustmq/robustmq, pull requests merged in 2025-05, with the labels that each got.

#1093 refactor: refactor service_mqtt in PC
  src/placement-center/src/mqtt/services/acl.rs
  src/placement-center/src/mqtt/services/connector.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/mqtt/services/subscribe.rs
  src/placement-center/src/mqtt/services/topic.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
Labels: Size: L, kind:refactor

#1090 test: Fix the case where the MQTT protocol test case fails
  Cargo.toml
  src/cmd/src/mqtt-server/server.rs
  src/delay-message/src/pop.rs
  src/grpc-clients/src/pool.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/response.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  tests/tests/mqtt_protocol/acl_test.rs
  tests/tests/mqtt_protocol/blacklist_test.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/content_type_test.rs
  tests/tests/mqtt_protocol/delay_publish_test.rs
  tests/tests/mqtt_protocol/qos_test.rs
  tests/tests/mqtt_protocol/req_resp_test.rs
  tests/tests/mqtt_protocol/retain_message_test.rs
  tests/tests/mqtt_protocol/schema_test.rs
  tests/tests/mqtt_protocol/share_sub_test.rs
  tests/tests/mqtt_protocol/sub_auto.rs
  tests/tests/mqtt_protocol/sub_exclusive_test.rs
  tests/tests/mqtt_protocol/sub_identifier_test.rs
  tests/tests/mqtt_protocol/sub_wildcards_test.rs
  tests/tests/mqtt_protocol/topic_alias_test.rs
  tests/tests/mqtt_protocol/topic_rewrite_test.rs
  tests/tests/mqtt_protocol/user_properties_test.rs
  tests/tests/mqtt_protocol/user_test.rs
Labels: Size: M, kind:test

#1094 feat: Fixed the kernel stalling bug
  src/mqtt-broker/src/subscribe/exclusive_push.rs
  tests/tests/mqtt_protocol/keep_alive_test.rs
  tests/tests/mqtt_protocol/sub_identifier_test.rs
Labels: kind:feat, Size: S

#1096 refactor: refactor grpc srvice in Mqtt
  src/mqtt-broker/src/admin/acl.rs
  src/mqtt-broker/src/admin/blacklist.rs
  src/mqtt-broker/src/admin/client.rs
  src/mqtt-broker/src/admin/connector.rs
  src/mqtt-broker/src/admin/schema.rs
  src/mqtt-broker/src/admin/session.rs
  src/mqtt-broker/src/admin/subscribe.rs
  src/mqtt-broker/src/admin/topic.rs
  src/mqtt-broker/src/admin/user.rs
  src/mqtt-broker/src/server/grpc/admin.rs
Labels: Size: L, kind:refactor

#1098 refactor: refactor service_journal.rs in PC
  src/placement-center/src/journal/services/segment.rs
  src/placement-center/src/journal/services/shard.rs
  src/placement-center/src/server/grpc/service_journal.rs
Labels: Size: M, kind:refactor

#1100 refactor: refactor service_openraft.rs in PC
  src/placement-center/src/raft/mod.rs
  src/placement-center/src/raft/services.rs
  src/placement-center/src/server/grpc/mod.rs
  src/placement-center/src/server/grpc/server.rs
  src/placement-center/src/server/grpc/service_openraft.rs
  src/placement-center/src/server/grpc/services_openraft.rs
Labels: Size: M, kind:refactor

#1102 refactor: refactor service_kv.rs in PC
  src/placement-center/src/kv/mod.rs
  src/placement-center/src/kv/services.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/server/grpc/service_kv.rs
Labels: Size: M, kind:refactor

#1104 refactor: refactor service_mqtt.rs in PC
  src/placement-center/src/mqtt/services/acl.rs
  src/placement-center/src/mqtt/services/connector.rs
  src/placement-center/src/mqtt/services/session.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/mqtt/services/subscribe.rs
  src/placement-center/src/mqtt/services/topic.rs
  src/placement-center/src/mqtt/services/user.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
Labels: Size: L, kind:refactor

#1106 refactor: add request validate and refactor serivice_inner in PC
  Cargo.lock
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/inner/mod.rs
  src/placement-center/src/inner/services.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/server/grpc/service_inner.rs
Labels: Size: L, kind:refactor

#1113 feat: Improve the topic list query interface for CLI and dashboard
  Cargo.lock
  Cargo.toml
  docs/en/RobustMQ-Command/Mqtt-Broker.md
  docs/zh/RobustMQ-Command/Mqtt-Broker.md
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/metadata-struct/src/mqtt/topic.rs
  src/delay-message/src/lib.rs
  src/mqtt-broker/src/admin/topic.rs
  src/mqtt-broker/src/server/grpc/admin.rs
Labels: kind:feat, Size: M

#1115 feat: Optimize the implementation of shared subscriptions
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/lastwill.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/offline_message.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/handler/sub_auto.rs
  src/mqtt-broker/src/handler/sub_exclusive.rs
  src/mqtt-broker/src/handler/sub_parse_topic.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/server/quic/response.rs
  src/mqtt-broker/src/server/quic/server.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/manager.rs
  src/mqtt-broker/src/subscribe/meta.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/mqtt-broker/src/subscribe/share/mod.rs
  src/mqtt-broker/src/subscribe/share/write.rs
  src/mqtt-broker/src/subscribe/share_follower_resub.rs
Labels: kind:feat, Size: XL

#1117 feat: Optimize the subscription code
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/manager.rs
  src/mqtt-broker/src/subscribe/meta.rs
  src/mqtt-broker/src/subscribe/mod.rs
  src/mqtt-broker/src/subscribe/push.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
Labels: kind:feat, Size: XL

#1112 feat: add system_topic
  docs/zh/RobustMQ-Command/Mqtt-Broker.md
  src/common/metadata-struct/src/mqtt/message.rs
  src/grpc-clients/src/lib.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/observability/system_topic/broker.rs
  src/mqtt-broker/src/observability/system_topic/mod.rs
  src/mqtt-broker/src/observability/system_topic/packet/bytes.rs
  src/mqtt-broker/src/observability/system_topic/packet/messages.rs
  src/mqtt-broker/src/observability/system_topic/packet/mod.rs
  src/mqtt-broker/src/observability/system_topic/packet/packets.rs
  src/mqtt-broker/src/observability/system_topic/stats/client.rs
  src/mqtt-broker/src/observability/system_topic/stats/mod.rs
  src/mqtt-broker/src/observability/system_topic/stats/route.rs
  src/mqtt-broker/src/observability/system_topic/stats/subscription.rs
  src/mqtt-broker/src/observability/system_topic/stats/topics.rs
Labels: kind:feat, Size: XL

#1120 chore: add quick single node startup mode
  .gitignore
  example/single-mqtt-cluster/README.md
  example/single-mqtt-cluster/certs/ca.pem
  example/single-mqtt-cluster/certs/cert.pem
  example/single-mqtt-cluster/certs/key.pem
  example/single-mqtt-cluster/journal-server/journal-server.toml
  example/single-mqtt-cluster/journal-server/journal-tracing.toml
  example/single-mqtt-cluster/mqtt-server/mqtt-server.toml
  example/single-mqtt-cluster/mqtt-server/mqtt-tracing.toml
  example/single-mqtt-cluster/placement-center/place-tracing.toml
  example/single-mqtt-cluster/placement-center/placement-center.toml
  example/single-mqtt-cluster/start.sh
  example/single-mqtt-cluster/stop.sh
Labels: Size: L, kind:chore

#1121 feat: add rocksDB metrics in pc
  src/placement-center/src/core/metrics.rs
  src/placement-center/src/raft/store/log_store.rs
  src/placement-center/src/raft/store/state_machine_store.rs
Labels: kind:feat, Size: M

#1125 test: fix broker_mqtt unit test in config
  src/common/base/src/config/broker_mqtt.rs
Labels: Size: M, kind:test

#1123 feat: Introduce the tokio console debugging tool
  Cargo.lock
  Cargo.toml
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/subscribe/manager.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/session_expire.rs
Labels: kind:feat, size/xs, Size: S, Size: M
