Repository robustmq/robustmq, pull requests merged in 2025-09, with the labels that each got.

#1345 test: Add test cases to the method of cache.rs
  src/mqtt-broker/src/handler/cache.rs
Labels: Size: M, kind:test

#1354 test: Add test cases for the MQTT Bridge module
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/greptimedb/sender.rs
  src/mqtt-broker/src/bridge/heartbeat.rs
  src/mqtt-broker/src/bridge/manager.rs
Labels: Size: M, kind:test

#1357 chore: cleanup redundancy format indicator check
  src/mqtt-broker/src/handler/validator.rs
Labels: Size: S, kind:chore

#1358 refactor: Reconfigure the command line and change it to make HTTP calls to the server side.
  Cargo.lock
  Cargo.toml
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  src/admin-server/API_DOCUMENTATION.md
  src/admin-server/src/mqtt/acl.rs
  src/admin-server/src/mqtt/blacklist.rs
  src/admin-server/src/mqtt/client.rs
  src/admin-server/src/mqtt/connector.rs
  src/admin-server/src/mqtt/schema.rs
  src/admin-server/src/mqtt/session.rs
  src/admin-server/src/mqtt/subscribe.rs
  src/admin-server/src/mqtt/system.rs
  src/admin-server/src/mqtt/topic.rs
  src/admin-server/src/mqtt/user.rs
  src/admin-server/src/request.rs
  src/admin-server/src/server.rs
  src/admin-server/src/tool/query.rs
  src/cli-command/Cargo.toml
  src/cli-command/src/client.rs
  src/cli-command/src/cluster.rs
  src/cli-command/src/lib.rs
  src/cli-command/src/mqtt.rs
  src/cmd/Cargo.toml
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/base/src/http_response.rs
Labels: Size: XL, kind:refactor

#1361 refactor: Organize the code and fix the test cases.
  src/broker-core/src/cluster.rs
  src/cli-bench/src/kv/utils.rs
  src/grpc-clients/src/lib.rs
  src/grpc-clients/src/meta/inner/call.rs
  src/grpc-clients/src/meta/inner/mod.rs
  src/grpc-clients/src/meta/journal/call.rs
  src/grpc-clients/src/meta/journal/mod.rs
  src/grpc-clients/src/meta/kv/call.rs
  src/grpc-clients/src/meta/kv/mod.rs
  src/grpc-clients/src/meta/mod.rs
  src/grpc-clients/src/meta/mqtt/call.rs
  src/grpc-clients/src/meta/mqtt/mod.rs
  src/grpc-clients/src/meta/openraft/call.rs
  src/grpc-clients/src/meta/openraft/mod.rs
  src/grpc-clients/src/pool.rs
  src/grpc-clients/tests/placement/journal/segment.rs
  src/grpc-clients/tests/placement/journal/shard.rs
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/grpc-clients/tests/placement/mqtt/kv_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_acl_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_blacklist_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_last_will_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_schema_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_session_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_topic_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_user_test.rs
  src/grpc-clients/tests/placement/mqtt/openraft_test.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/segment_meta.rs
  src/journal-server/src/core/segment_status.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/segment/scroll.rs
  src/meta-service/src/raft/network/connection.rs
  src/mqtt-broker/src/common/pkid_storage.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/storage/acl.rs
  src/mqtt-broker/src/storage/auto_subscribe.rs
  src/mqtt-broker/src/storage/blacklist.rs
  src/mqtt-broker/src/storage/connector.rs
  src/mqtt-broker/src/storage/schema.rs
  src/mqtt-broker/src/storage/session.rs
  src/mqtt-broker/src/storage/topic.rs
  src/mqtt-broker/src/storage/user.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/storage-adapter/src/journal/offset.rs
  src/storage-adapter/src/meta/mod.rs
  tests/tests/cluster.rs
  tests/tests/meta/share_sub.rs
  tests/tests/meta/topic_rewrite_rule.rs
  tests/tests/mqtt/storage/mod.rs
  tests/tests/mqtt/storage/session_test.rs
  tests/tests/mqtt/storage/topic_test.rs
  tests/tests/mqtt/storage/user_test.rs
Labels: Size: M, Size: L, kind:refactor

#1363 docs: Optimize the documentation related to the command line and API interfaces
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-Command/CLI_CLUSTER.md
  docs/en/RobustMQ-Command/CLI_COMMON.md
  docs/en/RobustMQ-Command/CLI_JOURNAL.md
  docs/en/RobustMQ-Command/CLI_MQTT.md
  docs/en/RobustMQ-Command/Mqtt-Broker.md
  docs/en/RobustMQ-Command/Overview.md
  docs/zh/RobustMQ-Command/CLI_CLUSTER.md
  docs/zh/RobustMQ-Command/CLI_COMMON.md
  docs/zh/RobustMQ-Command/CLI_JOURNAL.md
  docs/zh/RobustMQ-Command/CLI_MANUAL.md
  docs/zh/RobustMQ-Command/CLI_MQTT.md
  docs/zh/RobustMQ-Command/Mqtt-Broker.md
  docs/zh/RobustMQ-Command/Overview.md
Labels: kind:docs, Size: XL

#1366 fix: Fix the error in the document address.
  docs/en/ContributionGuide/ContributingDoc/Doc-Contribution-Guide.md
  docs/en/QuickGuide/mqtt/First-Task.md
  docs/zh/ContributionGuide/ContributingDoc/Doc-Contribution-Guide.md
  docs/zh/QuickGuide/mqtt/First-Task.md
Labels: kind:bug, Size: S

#1362 test: add quic connect test
  Cargo.lock
  src/admin-server/src/client.rs
  src/cli-command/src/mqtt/command.rs
  src/common/base/src/enum_type/mqtt/acl/mqtt_acl_blacklist_type.rs
  tests/Cargo.toml
  tests/tests/mqtt/protocol/mod.rs
  tests/tests/mqtt/protocol/quic_server/common.rs
  tests/tests/mqtt/protocol/quic_server/mod.rs
  tests/tests/mqtt/protocol/quic_server/quic_connect_test.rs
  tests/tests/mqtt/protocol/quic_server/quic_packet_test.rs
Labels: Size: M, kind:test

#1368 feat: Improve the Kafka protocol parsing
  Cargo.lock
  README.md
  config/server-tracing.toml
  docs/en/ContributionGuide/ContributingCode/Code-Structure.md
  docs/images/wechat-group.jpg
  docs/images/wechat-group.png
  docs/zh/ContributionGuide/ContributingCode/Code-Structure.md
  src/admin-server/Cargo.toml
  src/admin-server/src/mqtt/topic.rs
  src/admin-server/src/server.rs
  src/common/metadata-struct/src/mqtt/topic_rewrite_rule.rs
  src/meta-service/src/raft/route/mqtt.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/protocol/src/kafka/codec.rs
  src/protocol/src/kafka/packet.rs
Labels: kind:feat, Size: XL, Size: M

#1371 feat: Reconstruct the connection jitter record storage
  README.md
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/Blogs/01.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/zh/Blogs/01.md
  docs/zh/OverView/What-is-RobustMQ.md
Labels: kind:feat, Size: L

#1372 docs: Improve the documentation of the MQTT broker
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/Blogs/01.md
  docs/en/RobustMQ-MQTT/Dashboard.md
  docs/en/RobustMQ-MQTT/MQTTX-Guide.md
  docs/en/RobustMQ-MQTT/SDK/c-sdk.md
  docs/en/RobustMQ-MQTT/SDK/go-sdk.md
  docs/en/RobustMQ-MQTT/SDK/java-sdk.md
  docs/en/RobustMQ-MQTT/SDK/javascript-sdk.md
  docs/en/RobustMQ-MQTT/SDK/python-sdk.md
  docs/zh/Blogs/01.md
  docs/zh/RobustMQ-MQTT/Dashboard.md
  docs/zh/RobustMQ-MQTT/MQTTX-Guide.md
  docs/zh/RobustMQ-MQTT/Overview.md
  docs/zh/RobustMQ-MQTT/SDK/c-sdk.md
  docs/zh/RobustMQ-MQTT/SDK/go-sdk.md
  docs/zh/RobustMQ-MQTT/SDK/java-sdk.md
  docs/zh/RobustMQ-MQTT/SDK/javascript-sdk.md
  docs/zh/RobustMQ-MQTT/SDK/python-sdk.md
Labels: kind:docs, Size: XL

#1383 docs: @Ayanokoji-li Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1384 docs: @patwrall Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1385 docs: @flyswimmer Nice to meet you (#1384)
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1386 docs: @satori1995 Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1391 docs: @NuclEnergy Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, Size: S

#1390 docs: @WaterWhisperer Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1388 docs: @hzbnb Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs, Size: S

#1392 chore: sign myself
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: size/xs, kind:chore

#1393 docs: @chenxi2015 Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1394 docs: @yqingyu Nice to meet you
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1387 refactor: reconstruct flapping detect logs
  docs/zh/Blogs/04.md
  docs/zh/Blogs/05.md
  docs/zh/Blogs/06.md
  docs/zh/Blogs/07.md
  docs/zh/OverView/Why-RobustMQ.md
  src/admin-server/src/mqtt/system.rs
  src/admin-server/src/response/mqtt.rs
  src/admin-server/src/server.rs
  src/admin-server/src/state.rs
  src/broker-server/src/lib.rs
  src/cli-command/src/mqtt/command.rs
  src/common/config/src/config.rs
  src/common/config/src/default.rs
  src/common/rocksdb-engine/src/lib.rs
  src/meta-service/src/storage/journal/segment_meta.rs
  src/meta-service/src/storage/journal/shard.rs
  src/meta-service/src/storage/placement/cluster.rs
  src/meta-service/src/storage/placement/config.rs
  src/meta-service/src/storage/placement/idempotent.rs
  src/meta-service/src/storage/placement/kv.rs
  src/meta-service/src/storage/placement/node.rs
  src/meta-service/src/storage/placement/offset.rs
  src/meta-service/src/storage/placement/schema.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/flapping_detect.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/slow_subscribe.rs
  src/mqtt-broker/src/handler/system_alarm.rs
  src/mqtt-broker/src/security/auth/metadata.rs
  src/mqtt-broker/src/server/mod.rs
  src/mqtt-broker/src/storage/keys.rs
  src/mqtt-broker/src/storage/local.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
Labels: Size: M, Size: L, kind:refactor

#1395 refactor: Reconstruct slow subscription
  Cargo.lock
  Cargo.toml
  src/admin-server/src/mqtt/subscribe.rs
  src/common/config/src/config.rs
  src/common/config/src/default.rs
  src/common/rate-limit/Cargo.toml
  src/common/rate-limit/src/lib.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/common/metrics_cache.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/slow_subscribe.rs
  src/mqtt-broker/src/handler/sub_auto.rs
  src/mqtt-broker/src/handler/system_alarm.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/observability/mod.rs
  src/mqtt-broker/src/observability/slow/core.rs
  src/mqtt-broker/src/observability/slow/slow_subscribe_data.rs
  src/mqtt-broker/src/observability/slow/slow_subscribe_key.rs
  src/mqtt-broker/src/storage/keys.rs
  src/mqtt-broker/src/storage/local.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/mqtt-broker/src/system_topic/broker.rs
  src/mqtt-broker/src/system_topic/event.rs
  src/mqtt-broker/src/system_topic/mod.rs
  src/mqtt-broker/src/system_topic/packet/bytes.rs
  src/mqtt-broker/src/system_topic/packet/messages.rs
  src/mqtt-broker/src/system_topic/packet/mod.rs
  src/mqtt-broker/src/system_topic/packet/packets.rs
  src/mqtt-broker/src/system_topic/stats/client.rs
  src/mqtt-broker/src/system_topic/stats/mod.rs
  src/mqtt-broker/src/system_topic/stats/route.rs
  src/mqtt-broker/src/system_topic/stats/subscription.rs
  src/mqtt-broker/src/system_topic/stats/topics.rs
  src/mqtt-broker/src/system_topic/sysmon.rs
Labels: Size: XL, kind:refactor

#1397 docs: @codenohup Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1399 docs: @dwsio Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1400 feat: add dashboard static file serving to admin HTTP server
  Cargo.lock
  Cargo.toml
  src/admin-server/src/server.rs
Labels: kind:feat, Size: S

#1401 feat: Kernel integrated dashboard page
  docs/en/Api/CLUSTER.md
  docs/en/Api/COMMON.md
  docs/en/Api/MQTT.md
  docs/images/04.jpg
  docs/images/robustmq-architecture-overview.jpg
  docs/images/robustmq-architecture.jpg
  docs/zh/Api/CLUSTER.md
  docs/zh/Api/COMMON.md
  docs/zh/Api/MQTT.md
  docs/zh/Blogs/06.md
  scripts/build.sh
  src/admin-server/src/client.rs
  src/admin-server/src/lib.rs
  src/admin-server/src/path.rs
  src/admin-server/src/server.rs
Labels: kind:feat, Size: M, Size: L

#1404 chore: use `cargo-autoinherit` to de-duplicate the dependices.
  Cargo.toml
  src/common/base/Cargo.toml
  src/robustmq-macro/Cargo.toml
  tests/Cargo.toml
Labels: Size: S, kind:chore

#1406 docs:install protoc and zstd
  docs/en/QuickGuide/Build-and-Package.md
  docs/zh/QuickGuide/Build-and-Package.md
Labels: kind:docs, Size: S

#1407 feat: Add a variety of monitoring indicators
  Cargo.lock
  README.md
  docs/images/web-ui.png
  docs/zh/Blogs/03.md
  src/admin-server/Cargo.toml
  src/admin-server/src/mqtt/overview.rs
  src/admin-server/src/response/mqtt.rs
  src/admin-server/src/server.rs
  src/common/metrics/src/common.rs
  src/common/metrics/src/core/histogram.rs
  src/common/metrics/src/core/mod.rs
  src/common/metrics/src/http.rs
  src/common/metrics/src/lib.rs
Labels: kind:feat, Size: M

#1416 fix: Fix the Dockerfile to make it build and run normally
  docker/Dockerfile
Labels: kind:bug, size/xs

#1414 feat: Increase monitoring indicators
  Cargo.lock
  config/server.toml
  docs/en/QuickGuide/PublicMqttServer.md
  docs/zh/QuickGuide/PublicMqttServer.md
  src/admin-server/src/server.rs
  src/broker-server/src/grpc.rs
  src/common/metrics/Cargo.toml
  src/common/metrics/src/core/histogram.rs
  src/common/metrics/src/grpc.rs
  src/common/metrics/src/http.rs
  src/common/metrics/src/network.rs
Labels: kind:feat, Size: XL

#1423 docs: Improve the MQTT connector documentation
  docs/.vitepress/config.mts
  docs/.vitepress/src/configs/en.mts
  docs/.vitepress/src/configs/zh.mts
  docs/.vitepress/src/nav/en.mts
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/OverView/Diff-MQ.md
  docs/OverView/Diff-iggy.md
  docs/OverView/What-is-RobustMQ.md
  docs/OverView/Why-RobustMQ.md
  docs/OverView/index.md
  docs/en/RobustMQ-MQTT/Bridge/GreptimeDB.md
  docs/en/RobustMQ-MQTT/Bridge/Kafka.md
  docs/en/RobustMQ-MQTT/Bridge/LocalFile.md
  docs/en/RobustMQ-MQTT/Bridge/Overview.md
  docs/en/index.md
  docs/index.md
  docs/zh/RobustMQ-MQTT/Bridge/GreptimeDB.md
  docs/zh/RobustMQ-MQTT/Bridge/Kafka.md
  docs/zh/RobustMQ-MQTT/Bridge/LocalFile.md
  docs/zh/RobustMQ-MQTT/Bridge/Overview.md
  docs/zh/index.md
Labels: kind:docs, Size: XL

#1426 fix: Fix the issue of disordered styles in the front-end page.
  docs/.vitepress/config.mts
  docs/index.md
Labels: kind:bug

#1427 fix: Fix the issue of disordered styles in the front-end page.
  docs/.vitepress/config.mts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/layout-fix.css
  docs/index.md
Labels: kind:bug, size/xs, Size: M

#1432 refactor: use the built-in `r2d2` module of the `redis` crate to replace the `r2d2_redis` crate
  Cargo.lock
  Cargo.toml
  src/common/base/Cargo.toml
  src/common/base/src/error/common.rs
  src/common/third-driver/Cargo.toml
  src/common/third-driver/src/redis.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/error.rs
  src/mqtt-broker/src/security/storage/redis/mod.rs
Labels: Size: S, kind:refactor

#1434 fix: Fix the bugs in the document
  docs/en/Observability/Grafana-Configuration-Guide.md
  docs/en/Observability/Prometheus-Integration.md
  docs/zh/Observability/Grafana配置指南.md
  docs/zh/Observability/MQTT专用指标.md
  docs/zh/Observability/Prometheus接入.md
  docs/zh/Observability/基础设施指标.md
Labels: kind:bug

#1439 refactor: Code optimization and performance tuning
  .github/workflows/ig-all-test.yml
  Cargo.lock
  Cargo.toml
  config/server-tracing.toml
  config/server.toml
  config/version.ini
  docs/zh/Blogs/06.md
  docs/zh/Blogs/08.md
  scripts/INSTALL_GUIDE.md
  scripts/RELEASE_GUIDE.md
  scripts/bin-ig-test.sh
  scripts/build.sh
  scripts/release.sh
  src/amqp-broker/Cargo.toml
  src/common/base/Cargo.toml
  src/common/base/src/error/common.rs
  src/common/base/src/runtime.rs
  src/common/config/Cargo.toml
  src/common/config/src/default.rs
  src/common/metadata-struct/Cargo.toml
  src/common/metrics/Cargo.toml
  src/common/network-server/src/quic/acceptor.rs
  src/common/rocksdb-engine/Cargo.toml
  src/common/rocksdb-engine/src/lib.rs
  src/common/security/Cargo.toml
  src/grpc-clients/Cargo.toml
  src/grpc-clients/tests/journal/mod.rs
  src/grpc-clients/tests/journal/update_cache.rs
  src/grpc-clients/tests/mod.rs
  src/journal-server/Cargo.toml
  src/kafka-broker/Cargo.toml
  src/message-expire/Cargo.toml
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/protocol/Cargo.toml
  src/schema-register/Cargo.toml
  tests/Cargo.toml
  tests/src/common/mod.rs
  tests/src/common/utils.rs
  tests/src/lib.rs
  tests/tests/mqtt/protocol/common.rs
  tests/tests/mqtt/protocol/delay_publish_test.rs
  tests/tests/mqtt/protocol/keep_alive_test.rs
Labels: Size: XL, Size: M, kind:refactor

#1443 refactor: Optimize the packaging and building scripts
  docs/en/QuickGuide/Build-and-Package.md
  docs/en/VersionRecord/0.1.0-beta.md
  docs/en/VersionRecord/RobustMQ-0.2.0-RELEASE.md
  docs/en/VersionRecord/Summary-2024.md
  docs/zh/Blogs/08.md
  docs/zh/QuickGuide/Build-and-Package.md
  docs/zh/VersionRecord/0.1.0-beta.md
  docs/zh/VersionRecord/RobustMQ-0.2.0-RELEASE.md
  docs/zh/VersionRecord/Summary-2024.md
  scripts/BUILD.md
  scripts/RELEASE.md
  scripts/build.sh
  scripts/release.sh
Labels: Size: XL, kind:refactor
