Repository robustmq/robustmq, pull requests merged in 2025-10, with the labels that each got.

#1446 feat: add batch insert and upsert support for postgres bridge
  src/common/metadata-struct/src/mqtt/bridge/config_postgres.rs
  src/mqtt-broker/src/bridge/postgres/mod.rs
Labels: kind:feat, Size: M

#1448 docs: @reigadegr Nice to meet you
  docs/en/OverView/SignYourName.md
  docs/zh/OverView/SignYourName.md
Labels: kind:docs, size/xs

#1447 fix: Fix the page style issues
  docs/.vitepress/config.mts
  docs/.vitepress/theme/components/BadgeSection.vue
  docs/.vitepress/theme/components/GitHubStarsButton.vue
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/github-stars.js
  docs/.vitepress/theme/index.ts
  docs/en/RobustMQ-MQTT/Bridge/Overview.md
  docs/en/RobustMQ-MQTT/Bridge/PostgreSQL.md
  docs/en/index.md
  docs/images/command-print.png
  docs/index.md
  docs/zh/Blogs/08.md
  docs/zh/RobustMQ-MQTT/Bridge/Overview.md
  docs/zh/RobustMQ-MQTT/Bridge/PostgreSQL.md
  docs/zh/index.md
  src/cmd/src/broker-server/server.rs
  src/cmd/src/cli-command/command.rs
  src/common/base/src/version/logo.rs
Labels: kind:bug, Size: XL, Size: L

#1451 feat: Add `MongoDB` connector.
  Cargo.lock
  Cargo.toml
  deny.toml
  src/admin-server/src/mqtt/connector.rs
  src/common/metadata-struct/src/mqtt/bridge/config_mongodb.rs
  src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
  src/common/metadata-struct/src/mqtt/bridge/mod.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/bridge/mongodb/mod.rs
  src/mqtt-broker/src/handler/error.rs
Labels: kind:feat, Size: M

#1453 refactor: Optimize the network thread model and enhance performance
  config/server.toml
  src/admin-server/src/mqtt/topic.rs
  src/broker-core/src/heartbeat.rs
  src/common/base/src/tools.rs
  src/common/metadata-struct/src/connection.rs
  src/common/metrics/src/network.rs
  src/common/network-server/src/common/channel.rs
  src/common/network-server/src/common/handler.rs
  src/common/network-server/src/common/metric.rs
  src/common/network-server/src/common/response.rs
  src/common/network-server/src/common/tool.rs
  src/common/network-server/src/quic/server.rs
  src/common/network-server/src/tcp/server.rs
  src/meta-service/src/controller/journal/call_node.rs
  src/meta-service/src/controller/journal/mod.rs
  src/meta-service/src/controller/mqtt/call_broker.rs
  src/meta-service/src/controller/mqtt/connector/scheduler.rs
  src/meta-service/src/controller/mqtt/message_expire.rs
  src/meta-service/src/controller/mqtt/mod.rs
  src/meta-service/src/controller/mqtt/session_expire.rs
  src/meta-service/src/core/controller.rs
  src/meta-service/src/core/heartbeat.rs
  src/meta-service/src/lib.rs
  src/meta-service/src/raft/leadership.rs
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/heartbeat.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/common/metrics_cache.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/flapping_detect.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/sub_parse_topic.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/system_alarm.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/mqtt-broker/src/security/storage/sync.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/mqtt-broker/src/system_topic/mod.rs
Labels: Size: XL, Size: L, kind:refactor

#1455 feat: Add `RabbitMQ` connector.
  Cargo.lock
  Cargo.toml
  src/admin-server/src/mqtt/connector.rs
  src/common/metadata-struct/src/mqtt/bridge/config_rabbitmq.rs
  src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
  src/common/metadata-struct/src/mqtt/bridge/mod.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/bridge/rabbitmq/mod.rs
  src/mqtt-broker/src/handler/error.rs
Labels: kind:feat, Size: M

#1454 refactor: Optimize the performance of the kernel
  Cargo.lock
  Cargo.toml
  config/server.toml
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-MQTT/Bridge/MongoDB.md
  docs/en/RobustMQ-MQTT/Bridge/Overview.md
  docs/en/RobustMQ-MQTT/Bridge/RabbitMQ.md
  docs/zh/RobustMQ-MQTT/Bridge/MongoDB.md
  docs/zh/RobustMQ-MQTT/Bridge/Overview.md
  docs/zh/RobustMQ-MQTT/Bridge/RabbitMQ.md
  grafana/robustmq-mqtt-broker-dashboard.json
  src/common/config/src/config.rs
  src/common/config/src/default.rs
  src/common/metrics/src/network.rs
  src/common/network-server/src/common/channel.rs
  src/common/network-server/src/common/handler.rs
  src/common/network-server/src/common/metric.rs
  src/common/network-server/src/common/response.rs
  src/meta-service/src/controller/mqtt/message_expire.rs
  src/meta-service/src/controller/mqtt/mod.rs
  src/mqtt-broker/src/common/tool.rs
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/response.rs
  tests/tests/mqtt/protocol/keep_alive_test.rs
  tests/tests/mqtt/protocol/lastwill_message_test.rs
  tests/tests/mqtt/protocol/session_expire.rs
Labels: Size: XL, Size: M, kind:refactor

#1456 refactor: Optimize performance && Fix the failure of unit tests
  src/admin-server/src/mqtt/topic.rs
  src/meta-service/src/controller/mqtt/mod.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/handler/topic_rewrite.rs
  tests/tests/mqtt/protocol/acl_test.rs
  tests/tests/mqtt/protocol/blacklist_test.rs
  tests/tests/mqtt/protocol/common.rs
  tests/tests/mqtt/protocol/flapping_detect_test.rs
  tests/tests/mqtt/protocol/schema_test.rs
  tests/tests/mqtt/protocol/session_expire.rs
  tests/tests/mqtt/protocol/sub_auto.rs
  tests/tests/mqtt/protocol/sub_identifier_test.rs
  tests/tests/mqtt/protocol/topic_rewrite_test.rs
  tests/tests/mqtt/protocol/user_test.rs
Labels: Size: S, Size: M, kind:refactor

#1457 refactor: Optimize the build script && Fix performance issues
  config/server.toml
  docs/images/wechat-group.jpg
  grafana/robustmq-mqtt-broker-dashboard.json
  scripts/build.sh
  scripts/release.sh
Labels: Size: M, kind:refactor
