Repository robustmq/robustmq, pull requests merged in 2025-02, with the labels that each got.

#820 docs: add comments in journal server
  src/journal-server/src/core/shard.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/server/connection.rs
  src/journal-server/src/server/connection_manager.rs
  src/journal-server/src/server/tcp/handler.rs
  src/journal-server/src/server/tcp/response.rs
  src/journal-server/src/server/tcp/server.rs
  src/journal-server/src/server/tcp/tcp_server.rs
Labels: kind:docs, Size: S

#823 feat: Implement MinIO Storage Adapter
  Cargo.lock
  Cargo.toml
  src/common/base/Cargo.toml
  src/common/base/src/error/common.rs
  src/storage-adapter/Cargo.toml
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/minio/mod.rs
Labels: kind:feat, Size: L

#822 docs: stable release planning
  config/mqtt-server.toml
  docs/.design/plan/mqtt-stable-to-do.md
  docs/.vitepress/src/sidebars/zh.mts
  docs/zh/OverView/Welcome.md
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/flow_control.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/security/login/mod.rs
  src/mqtt-broker/src/server/connection.rs
Labels: kind:docs, Size: M

#826 perf: Optimize MinIO performance
  docs/.design/storage-adapter/minio.md
Labels: Size: S, kind:perf

#829 docs: register_node under mqtt-broker-server
  .github/ISSUE_TEMPLATE/enhancement.yml
  docs/.design/module/mqtt broker/GRPC.md
  docs/images/WechatGroup.png
  src/journal-server/src/segment/write.rs
  src/mqtt-broker/src/lib.rs
  src/placement-center/src/server/grpc/service_inner.rs
Labels: kind:docs, Size: S

#830 refactor: Refactored the metrics section.
  Cargo.lock
  src/common/base/Cargo.toml
  src/common/base/src/metrics/mod.rs
  src/common/base/src/metrics/registry.rs
  src/mqtt-broker/src/observability/metrics/event_metrics.rs
  src/mqtt-broker/src/observability/metrics/mod.rs
  src/mqtt-broker/src/observability/metrics/packets.rs
  src/mqtt-broker/src/observability/metrics/server.rs
Labels: Size: XL, kind:refactor

#836 feat: Optimizing the subscription process
  src/common/metadata-struct/src/mqtt/subscribe_data.rs
  src/common/metadata-struct/src/mqtt/topic.rs
  src/grpc-clients/src/placement/mqtt/call.rs
  src/grpc-clients/src/placement/mqtt/mod.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_topic_test.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/sub_exclusive.rs
  src/mqtt-broker/src/handler/sub_parse_topic.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/acl/mod.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/subscribe/sub_share_follower.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/placement-center/src/storage/mqtt/topic.rs
  tests/tests/mqtt_protocol/connect34_test.rs
Labels: kind:feat, Size: XL

#844 feat: Offline message development
  config/mqtt-server.toml
  src/common/metadata-struct/src/mqtt/cluster.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/heartbreat.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/offline_message.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/handler/sub_exclusive.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/handler/user.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/subscribe/exclusive_push.rs
  src/mqtt-broker/src/subscribe/mod.rs
  src/mqtt-broker/src/subscribe/share_follower_resub.rs
  src/mqtt-broker/src/subscribe/share_leader_push.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/mqtt-broker/src/subscribe/subscribe_manager.rs
  src/mqtt-broker/src/subscribe/subscriber.rs
Labels: kind:feat, Size: XL

#850 docs: Logo dev
  README.md
  docs/en/index.md
  docs/zh/index.md
Labels: kind:docs, Size: S

#854 refactor(startup shell): startup script bin/robust-server refactor . add more argument validation checks
  bin/robust-server
Labels: Size: M, kind:refactor

#859 fix: fix flapping detect e2e test error
  .pre-commit-config.yaml
  config/journal-server.toml
  docs/.design/plan/mqtt-stable-to-do.md
  docs/en/ContributionGuide/ContributingCode/Cargo-Running.md
  docs/images/Cargo-Running-run-journal-server-3.png
  docs/images/Cargo-Running-run-mqtt-server-2.png
  docs/images/WechatGroup.png
  docs/zh/ContributionGuide/ContributingCode/Cargo-Running.md
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/handler/delay_message.rs
  src/mqtt-broker/src/handler/flapping_detect.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/security/acl/metadata.rs
  tests/tests/mqtt_client/flapping_detect_test.rs
  tests/tests/mqtt_protocol/connect34_test.rs
Labels: kind:bug, Size: M

#860 docs:tidy up doc in QuickGuide
  docs/en/QuickGuide/Run-Cluster-Mode.md
  docs/en/QuickGuide/Run-Standalone-Mode.md
  docs/zh/QuickGuide/Run-Cluster-Mode.md
  docs/zh/QuickGuide/Run-Standalone-Mode.md
Labels: kind:docs, Size: S

#865 feat: dynamic configuration and the local static configuration are merged
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/metadata-struct/src/mqtt/cluster.rs
  src/mqtt-broker/src/handler/cluster_config.rs
Labels: kind:feat, Size: M

#864 feat: MQTT Connector data integration framework developmen
  Cargo.lock
  Cargo.toml
  src/common/metadata-struct/src/mqtt/bridge/config_kafka.rs
  src/common/metadata-struct/src/mqtt/bridge/connector.rs
  src/mqtt-bridge/elasticsearch/Cargo.toml
  src/mqtt-bridge/kafka/Cargo.toml
  src/mqtt-bridge/kafka/src/lib.rs
  src/mqtt-bridge/kafka/tests/mod.rs
  src/mqtt-bridge/redis/Cargo.toml
  src/mqtt-bridge/redis/src/lib.rs
  src/mqtt-bridge/redis/tests/mod.rs
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/file/mod.rs
  src/mqtt-broker/src/bridge/kafka/mod.rs
  src/mqtt-broker/src/bridge/manager.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/mqtt/connector/heartbeat.rs
  src/placement-center/src/mqtt/connector/mod.rs
  src/placement-center/src/mqtt/connector/request.rs
  src/placement-center/src/mqtt/connector/scheduler.rs
  src/placement-center/src/mqtt/mod.rs
  src/placement-center/src/mqtt/services/mod.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/protocol/src/broker_mqtt/proto/inner.proto
  src/protocol/src/placement_center/proto/mqtt.proto
  tests/tests/mqtt_protocol/connect34_test.rs
Labels: kind:feat, Size: L

#867 feat: MQTT Connector data integration framework development
  src/common/metadata-struct/src/mqtt/bridge/connector.rs
  src/common/metadata-struct/src/mqtt/bridge/status.rs
  src/grpc-clients/src/placement/mqtt/call.rs
  src/grpc-clients/src/placement/mqtt/mod.rs
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/file/mod.rs
  src/mqtt-broker/src/bridge/heartbeat.rs
  src/mqtt-broker/src/bridge/manager.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/bridge/request.rs
  src/mqtt-broker/src/observability/slow/request.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/admin/mod.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/storage/connector.rs
  src/mqtt-broker/src/storage/mod.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  src/protocol/src/placement_center/proto/mqtt.proto
Labels: kind:feat, Size: L

#869 feat: Optimize the mqtt and journal module code in grpc client
  src/cli-command/src/mqtt.rs
  src/grpc-clients/src/journal/admin/call.rs
  src/grpc-clients/src/journal/admin/mod.rs
  src/grpc-clients/src/journal/inner/call.rs
  src/grpc-clients/src/journal/inner/mod.rs
  src/grpc-clients/src/journal/mod.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/grpc-clients/src/mqtt/inner/call.rs
  src/grpc-clients/src/mqtt/inner/mod.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
Labels: kind:feat, Size: L

#870 fix: Formatting your code better
  src/protocol/src/mqtt/mqttv4/connect.rs
  src/protocol/src/mqtt/mqttv4/publish.rs
  src/protocol/src/mqtt/mqttv5/connect.rs
  src/protocol/src/mqtt/mqttv5/publish.rs
  src/protocol/src/mqtt/mqttv5/subscribe.rs
Labels: kind:bug, Size: S

#871 feat: connector CLI GRPC
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/metadata-struct/src/mqtt/bridge/connector.rs
  src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
  src/common/metadata-struct/src/mqtt/bridge/status.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
Labels: kind:feat, Size: M

#873 feat: load connector info from PC to MQTT broker cache
  src/grpc-clients/tests/placement/mqtt/mod.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/storage/connector.rs
Labels: kind:feat, Size: M

#878 feat: MQTT supports the function of delayed message publishing
  Cargo.lock
  Cargo.toml
  src/amqp-plugins/Cargo.toml
  src/common/metadata-struct/src/adapter/record.rs
  src/delay-message/Cargo.toml
  src/delay-message/src/build.rs
  src/delay-message/src/lib.rs
  src/delay-message/src/pop.rs
  src/delay-message/tests/delay.rs
  src/delay-message/tests/mod.rs
  src/journal-client/src/client.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-edge/tests/mod.rs
  src/storage-adapter/src/journal/mod.rs
  src/storage-adapter/src/memory/mod.rs
  src/storage-adapter/src/minio/mod.rs
  src/storage-adapter/src/mysql/mod.rs
  src/storage-adapter/src/rocksdb/mod.rs
  src/storage-adapter/src/storage.rs
Labels: kind:feat, Size: L

#882 feat: MQTT supports the function of delayed message publishing
  Cargo.lock
  Cargo.toml
  src/delay-message/src/build.rs
  src/delay-message/src/lib.rs
  src/delay-message/src/pop.rs
  src/idempotent-message/Cargo.toml
  src/idempotent-message/src/lib.rs
  src/idempotent-message/tests/mod.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/delay_message.rs
  src/mqtt-broker/src/handler/error.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/offline_message.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/storage-adapter/src/journal/mod.rs
  src/storage-adapter/src/memory/mod.rs
  src/storage-adapter/src/minio/mod.rs
  src/storage-adapter/src/mysql/mod.rs
  src/storage-adapter/src/rocksdb/mod.rs
  src/storage-adapter/src/storage.rs
Labels: kind:feat, Size: M

#883 docs: Add delay message documentation
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-MQTT/DelayMessage.md
  docs/zh/RobustMQ-MQTT/DelayMessage.md
Labels: kind:docs, Size: S

#886 docs: Add the MQTT Overview document
  docs/.DS_Store
  docs/.design/plan/mqtt-stable-to-do.md
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-Kafka/Overview.md
  docs/en/RobustMQ-MQTT/Overview.md
  docs/images/doc-image5.png
  docs/zh/RobustMQ-Kafka/Overview.md
  docs/zh/RobustMQ-MQTT/Overview.md
  src/protocol/src/kafka/mod.rs
  src/protocol/src/lib.rs
Labels: kind:docs

#888 style: fix code style and doc style
  docs/en/RobustMQ-MQTT/DelayMessage.md
  docs/zh/RobustMQ-Command/Mqtt-Broker.md
  docs/zh/RobustMQ-MQTT/DelayMessage.md
  src/protocol/src/kafka/mod.rs
Labels: Size: M, kind:style

#891 feat: load mqtt connector to PC MQTT cache
  src/placement-center/src/mqtt/cache.rs
Labels: kind:feat, size/xs
