Repository robustmq/robustmq, pull requests merged in 2025-06, with the labels that each got.

#1126 refactor: Fix the issue of failed test cases
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/metadata-struct/src/mqtt/cluster.rs
  src/mqtt-broker/src/handler/cluster_config.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/session.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/connect5_test.rs
  tests/tests/mqtt_protocol/lastwill_message_test.rs
  tests/tests/mqtt_protocol/session_expire.rs
Labels: Size: S, Size: M, kind:refactor

#1127 fix: Fixed the issue where the MQTT test case failed on the second run
  config/log-config/mqtt-tracing.toml
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/grpc-clients/src/pool.rs
  src/mqtt-broker/src/handler/error.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
Labels: kind:bug, Size: S, Size: M

#1133 fix: Fix typos errors in pre-commit and _typos.toml - close #1053
  _typos.toml
  src/mqtt-broker/src/observability/metrics/packets.rs
  src/placement-center/src/raft/raft_node.rs
  src/placement-center/src/raft/store/state_machine_store.rs
  src/protocol/src/mqtt/mqttv5/connect.rs
  src/protocol/src/mqtt/mqttv5/publish.rs
Labels: kind:bug, Size: S

#1134 docs: Fix link to troubleshooting page
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
Labels: kind:docs, size/xs

#1135 feat: initialize the pkg macro in robustmq
  Cargo.lock
  Cargo.toml
  src/robustmq-macro/Cargo.toml
  src/robustmq-macro/src/lib.rs
Labels: kind:feat, Size: S

#1138 refactor: Initial impl of configuring `tokio-console` support thru config file
  Cargo.lock
  Cargo.toml
  config/log-config/journal-tracing.toml
  config/log-config/mqtt-tracing.toml
  config/log-config/place-tracing.toml
  docs/en/ContributionGuide/ContributingCode/Troubleshooting.md
  docs/zh/ContributionGuide/ContributingCode/Troubleshooting.md
  src/common/base/src/error/log_config.rs
  src/common/base/src/logging/config.rs
  src/common/base/src/logging/console.rs
  src/common/base/src/logging/fmt.rs
  src/common/base/src/logging/mod.rs
  src/common/base/src/logging/rolling_file.rs
  src/common/base/src/logging/tokio_console.rs
Labels: Size: L, kind:refactor

#1140 fix: Disable TokioConsole entry in logging config by default
  config/log-config/mqtt-tracing.toml
  config/log-config/place-tracing.toml
Labels: kind:bug, Size: S

#1144 chore: fix log config change configuration
  example/single-mqtt-cluster/journal-server/journal-tracing.toml
  example/single-mqtt-cluster/mqtt-server/mqtt-tracing.toml
  example/single-mqtt-cluster/placement-center/place-tracing.toml
Labels: Size: S, kind:chore

#1145 feat: add time consumption metrics for mqtt-broker
  src/mqtt-broker/src/observability/metrics/server.rs
  src/mqtt-broker/src/server/packet.rs
  src/mqtt-broker/src/server/quic/handler.rs
  src/mqtt-broker/src/server/quic/response.rs
  src/mqtt-broker/src/server/tcp/handler.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/push.rs
Labels: kind:feat, Size: M

#1142 fix: Optimize the kernel issues discovered during the pressure testing process
  config/mqtt-server.toml
  src/common/base/src/config/broker_mqtt.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/quic/handler.rs
  src/mqtt-broker/src/server/tcp/handler.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/push.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  tests/tests/mqtt_protocol/keep_alive_test.rs
Labels: kind:bug, Size: M

#1149 chore: add cargo expand tool for unit test workflow
  .github/workflows/unit-test.yml
Labels: size/xs, kind:chore

#1147 fix: Optimize the logic of kernel stability
  .gitignore
  Cargo.lock
  Cargo.toml
  config/mqtt-server.toml
  src/common/base/src/config/broker_mqtt.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/lastwill.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/push.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
  tests/tests/mqtt_protocol/sub_wildcards_test.rs
Labels: kind:bug, Size: S, Size: M

#1151 feat: System alarm gRpc Interface
  Cargo.lock
  Cargo.toml
  docs/zh/RobustMQ-MQTT/SystemAlarm.md
  src/cli-command/src/mqtt.rs
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/metadata-struct/src/mqtt/cluster.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/admin/observability.rs
  src/mqtt-broker/src/handler/cluster_config.rs
  src/mqtt-broker/src/handler/lastwill.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  tests/tests/mqtt_client/mod.rs
  tests/tests/mqtt_client/system_alarm_test.rs
Labels: kind:feat, Size: L

#1158 test: fix grpc client test in placement server
  Cargo.lock
  Cargo.toml
  src/placement-center/src/server/grpc/service_mqtt.rs
  tests/tests/place_server/grpc_clients_test.rs
Labels: Size: S, kind:test

#1161 fix: Fix the tcp connection bug
  config/mqtt-server.toml
  src/mqtt-broker/src/observability/metrics/server.rs
  src/mqtt-broker/src/server/connection.rs
  src/mqtt-broker/src/server/metric.rs
  src/mqtt-broker/src/server/quic/response.rs
  src/mqtt-broker/src/server/tcp/handler.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/server/tcp/tcp_server.rs
Labels: kind:bug, Size: S, Size: M

#1160 feat: add impl expand validate stmt for validate_req
  src/robustmq-macro/src/lib.rs
  src/robustmq-macro/src/parse.rs
  src/robustmq-macro/src/tools.rs
  src/robustmq-macro/src/validate_req.rs
  src/robustmq-macro/tests/expand.rs
  src/robustmq-macro/tests/validate_req/expand/fn_success.expanded.rs
  src/robustmq-macro/tests/validate_req/expand/fn_success.rs
  src/robustmq-macro/tests/validate_req/expand/impl_success.expanded.rs
  src/robustmq-macro/tests/validate_req/expand/impl_success.rs
Labels: kind:feat, Size: L

#1163 refactor: refactor inner.rs in mqtt-broker
  src/mqtt-broker/src/handler/error.rs
  src/mqtt-broker/src/inner/mod.rs
  src/mqtt-broker/src/inner/services.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/inner.rs
Labels: Size: M, kind:refactor

#1168 ci: migrate the command-actbot file to the workflow dir
  .github/workflows/command-actbot.yml
Labels: size/xs, kind:ci

#1164 feat: system alarm
  Cargo.lock
  bin/robust-ctl
  config/mqtt-server.toml
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-MQTT/SystemAlarm.md
  docs/images/WechatGroup.jpg
  docs/zh/RobustMQ-MQTT/SystemAlarm.md
  src/cli-bench/src/kv/get.rs
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/config/src/mqtt/default.rs
  src/common/config/src/mqtt/mod.rs
  src/mqtt-broker/src/admin/observability.rs
  src/mqtt-broker/src/observability/system_topic/mod.rs
  src/mqtt-broker/src/observability/system_topic/sysmon.rs
  tests/tests/mqtt_client/system_alarm_test.rs
Labels: kind:feat, Size: M

#1170 docs: Improve readme readability
  README.md
Labels: kind:docs, Size: S

#1171 docs: add sign off doc to contributor guide
  Cargo.lock
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
Labels: kind:docs, Size: S

#1175 docs: add sign off doc to contributor guide(en)
  docs/en/ContributionGuide/GitHub-Contribution-Guide.md
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
Labels: kind:docs, Size: S

#1174 fix: bug fix for shared subscription code
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/server/tcp/v1/server.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/manager.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/share_sub_test.rs
Labels: kind:bug, Size: M

#1180 docs: update discord link
  README.md
Labels: kind:docs, size/xs

#1182 feat: cli-bench supports kv bench set
  src/cli-bench/src/kv/mod.rs
  src/cli-bench/src/kv/set.rs
Labels: kind:feat, Size: M

#1181 refactor: replace the wechat ID
  docs/images/wechat.jpg
Labels: size/xs, kind:refactor

#1189 fix: Optimize and fix the bugs in the smooth exit program
  src/journal-server/src/index/build.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/observability/system_topic/mod.rs
  src/mqtt-broker/src/observability/system_topic/sysmon.rs
Labels: kind:bug, Size: S

#1191 refactor: Add the "admin get status" interface
  Cargo.lock
  src/cli-command/src/mqtt.rs
  src/common/metadata-struct/src/journal/node_extend.rs
  src/common/metadata-struct/src/mqtt/node_extend.rs
  src/common/metadata-struct/src/placement/node.rs
  src/grpc-clients/tests/placement/journal/segment.rs
  src/grpc-clients/tests/placement/journal/shard.rs
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/lib.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/handler/cache.rs
  src/mqtt-broker/src/handler/dynamic_cache.rs
  src/mqtt-broker/src/handler/heartbreat.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/storage/cluster.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/journal/services/segment.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/robustmq-macro/tests/expand.rs
  tests/tests/mqtt_server/cluster_storage_test.rs
  tests/tests/place_server/broker_heartbeat_test.rs
  tests/tests/place_server/cluster_node_test.rs
  tests/tests/place_server/common.rs
  tests/tests/place_server/grpc_clients_test.rs
  tests/tests/place_server/share_sub.rs
Labels: Size: M, Size: L, kind:refactor

#1194 fix: Fix the cargo dependency error
  Cargo.lock
  Cargo.toml
Labels: kind:bug, size/xs

#1196 refactor: Optimize the running logic of the subscription thread
  Cargo.lock
  Cargo.toml
  example/mqtt-cluster/mqtt-server/log/mqtt-tracing-1.toml
  example/mqtt-cluster/mqtt-server/log/mqtt-tracing-2.toml
  example/mqtt-cluster/mqtt-server/log/mqtt-tracing-3.toml
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  src/common/metadata-struct/src/mqtt/subscribe_data.rs
  src/mqtt-broker/src/handler/dynamic_cache.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/tcp/v1/channel.rs
  src/mqtt-broker/src/server/tcp/v1/common.rs
  src/mqtt-broker/src/server/tcp/v1/handler.rs
  src/mqtt-broker/src/server/tcp/v1/response.rs
  src/mqtt-broker/src/server/tcp/v1/server.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/manager.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
Labels: Size: M, Size: L, kind:refactor

#1198 refactor: refactor amin.rs in mqtt-broker
  src/mqtt-broker/src/admin/acl.rs
  src/mqtt-broker/src/admin/blacklist.rs
  src/mqtt-broker/src/admin/client.rs
  src/mqtt-broker/src/admin/cluster.rs
  src/mqtt-broker/src/admin/connector.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/admin/observability.rs
  src/mqtt-broker/src/admin/schema.rs
  src/mqtt-broker/src/admin/session.rs
  src/mqtt-broker/src/admin/subscribe.rs
  src/mqtt-broker/src/admin/topic.rs
  src/mqtt-broker/src/admin/user.rs
  src/mqtt-broker/src/server/grpc/admin.rs
Labels: Size: L, kind:refactor

#1201 docs: add ask deepwiki
  README.md
Labels: kind:docs, size/xs
