Repository robustmq/robustmq, pull requests merged in 2025-08, with the labels that each got.

#1320 feat: Implement robustmq operator and dockerfile
  .dockerignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  _typos.toml
  benches/test.rs
  docker/.dockerignore
  docker/Dockerfile
  docker/README.md
  docker/docker-compose.yml
  operator/.gitignore
  operator/Dockerfile
  operator/Makefile
  operator/README.md
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/robustmq_types.go
  operator/boilerplate.go.txt
  operator/controllers/deployments.go
  operator/controllers/robustmq_controller.go
  operator/controllers/robustmq_controller_test.go
  operator/controllers/services.go
  operator/controllers/status.go
  operator/controllers/suite_test.go
  operator/deploy.sh
  operator/go.mod
  operator/main.go
  operator/robustmq.yaml
  operator/sample-robustmq.yaml
  operator/undeploy.sh
  scripts/check-place-status.sh
  scripts/install.sh
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
Labels: kind:feat, Size: XL

#1322 feat: Develop build, install, and release scripts
  Cargo.lock
  Cargo.toml
  scripts/INSTALL_GUIDE.md
  scripts/RELEASE_GUIDE.md
  scripts/build-release.sh
  scripts/build.sh
  scripts/install.sh
  scripts/release.sh
Labels: kind:feat, Size: XL

#1327 fix: Fix the errors in the test cases
  Cargo.lock
  Cargo.toml
  README.md
  config/server-tracing.toml
  docs/images/wechat-group.jpg
  docs/images/wechat-group.png
  src/mqtt-broker/src/handler/heartbeat.rs
  src/mqtt-broker/src/server/common/response.rs
  src/mqtt-broker/src/server/tcp/v1/server.rs
  tests/tests/mqtt_protocol/common.rs
Labels: kind:bug, Size: M

#1326 refactor: refactor the feature of slow subscribe record
  Cargo.lock
  README.md
  grafana/README.md
  grafana/docker-compose.monitoring.yml
  grafana/prometheus-config-example.yml
  grafana/robustmq-alerts.yml
  grafana/robustmq-mqtt-broker-dashboard.json
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/base/src/enum_type/delay_type.rs
  src/common/base/src/enum_type/mod.rs
  src/common/config/src/config.rs
  src/common/config/src/default.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/mqtt-broker/src/admin/observability.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/common/concurrent_btree_map.rs
  src/mqtt-broker/src/common/metrics_cache.rs
  src/mqtt-broker/src/common/mod.rs
  src/mqtt-broker/src/handler/dynamic_config.rs
  src/mqtt-broker/src/observability/slow/core.rs
  src/mqtt-broker/src/observability/slow/mod.rs
  src/mqtt-broker/src/observability/slow/request.rs
  src/mqtt-broker/src/observability/slow/slow_subscribe_data.rs
  src/mqtt-broker/src/observability/slow/slow_subscribe_key.rs
  src/mqtt-broker/src/observability/slow/sub.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/push.rs
  tests/tests/mqtt_server/observability/mod.rs
  tests/tests/mqtt_server/observability/slow_sub_test.rs
Labels: Size: XL, kind:refactor

#1334 docs: Update the official website documentation
  Cargo.lock
  docs/en/OverView/Diff-MQ.md
  docs/en/OverView/Diff-iggy.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/zh/OverView/Diff-MQ.md
  docs/zh/OverView/Diff-iggy.md
  docs/zh/OverView/What-is-RobustMQ.md
  src/common/base/Cargo.toml
  src/common/base/src/error/common.rs
  src/common/network-server/Cargo.toml
  src/common/network-server/src/common/mod.rs
  src/common/network-server/src/common/tcp_acceptor.rs
  src/common/network-server/src/common/tls_acceptor.rs
  src/common/network-server/src/common/tool.rs
Labels: kind:docs, Size: XL

#1339 feat: Add GreptimeDB connector for MQTT.
  Cargo.lock
  Cargo.toml
  src/common/metadata-struct/src/mqtt/bridge/config_greptimedb.rs
  src/common/metadata-struct/src/mqtt/bridge/connector.rs
  src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
  src/common/metadata-struct/src/mqtt/bridge/mod.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/admin/connector.rs
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/greptimedb/mod.rs
  src/mqtt-broker/src/bridge/greptimedb/sender.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/handler/error.rs
Labels: kind:feat, Size: M
