Repository robustmq/robustmq, pull requests merged in 2025-01, with the labels that each got.

#729 docs: add flapping-detect design logic
  docs/.design/logic/flapping-detect.md
Labels: Size: S

#730 docs: change readme.md
  README.md
  docs/images/WechatGroup.jpg
  docs/images/WechatGroup.png
  docs/images/wechat.jpg
Labels: size/xs

#731 feat: added Docker and Kubernetes startup
  .pre-commit-config.yaml
  Dockerfile
  docs/zh/QuickGuide/Run-Docker-Mode.md
  docs/zh/QuickGuide/Run-K8S-Mode.md
  example/test-network-docker/compose/compose-test-net.yaml
  example/test-network-docker/compose/config/cluster/mqtt-server/node-1.toml
  example/test-network-docker/compose/config/cluster/mqtt-server/node-2.toml
  example/test-network-docker/compose/config/cluster/mqtt-server/node-3.toml
  example/test-network-docker/compose/config/cluster/placement-center/node-1.toml
  example/test-network-docker/compose/config/cluster/placement-center/node-2.toml
  example/test-network-docker/compose/config/cluster/placement-center/node-3.toml
  example/test-network-docker/start.sh
  example/test-network-k8s/kube/cert-manager.yaml
  example/test-network-k8s/kube/cfg-mqtt-server.yaml
  example/test-network-k8s/kube/cfg-placement-center.yaml
  example/test-network-k8s/kube/ingress-nginx-robustmq-kind.yaml
  example/test-network-k8s/kube/mqtt-server-ingress.yaml
  example/test-network-k8s/kube/mqtt-server.yaml
  example/test-network-k8s/kube/placement-center.yaml
  example/test-network-k8s/network.sh
  example/test-network-k8s/scripts/cluster.sh
  example/test-network-k8s/scripts/config.sh
  example/test-network-k8s/scripts/docker.sh
  example/test-network-k8s/scripts/kind.sh
  example/test-network-k8s/scripts/robustmq.sh
  example/test-network-k8s/scripts/util.sh
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/common.rs
  src/common/base/src/config/placement_center.rs
Labels: Size: XL

#733 docs: fix docs path error
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/Architect/Configuration/Placement-Center.md
  docs/en/Architect/Overview.md
  docs/en/ContributionGuide/Pull-Request-Example.md
  docs/zh/Architect/Broker-Server.md
  docs/zh/Architect/Configuration/Mqtt-Server.md
  docs/zh/Architect/Configuration/Placement-Center.md
  docs/zh/Architect/Journal-Server.md
  docs/zh/Architect/Overview.md
  docs/zh/Architect/Placement-Center.md
  docs/zh/Architect/Test-Case.md
  docs/zh/ContributionGuide/Build-Develop-Env.md
  docs/zh/ContributionGuide/Cargo-Running.md
  docs/zh/ContributionGuide/Code-Structure.md
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
  docs/zh/ContributionGuide/Pull-Request-Example.md
  docs/zh/ContributionGuide/VsCode-Running.md
  docs/zh/OverView/RoadMap.md
  docs/zh/OverView/What-is-RobustMQ.md
  docs/zh/OverView/Why-RobustMQ.md
  docs/zh/QuickGuide/Overview.md
  docs/zh/QuickGuide/Run-Cluster-Mode.md
  docs/zh/QuickGuide/Run-Standalone-Mode.md
  docs/zh/RobustMQ-MQTT/Overview.md
Labels: Size: S

#735 chore: Add validation to the node_list method & test
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#734 docs: Quick Start Documentation
  bin/robust-server
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/QuickGuide/Run-Cluster-Mode.md
  docs/en/QuickGuide/Run-Docker-Mode.md
  docs/en/QuickGuide/Run-K8S-Mode.md
  docs/en/QuickGuide/Run-Standalone-Mode.md
  docs/zh/QuickGuide/Run-Cluster-Mode.md
  docs/zh/QuickGuide/Run-Standalone-Mode.md
Labels: Size: M

#736 chore: Add validation to exists_idempotent_data and test
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#744 build: fix a template error in the placeholder of task list
  .github/ISSUE_TEMPLATE/umbrella.yml
Labels: size/xs, kind:build

#745 chore: Add validation to the delete_resource_config method and test
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/server/grpc/validate.rs
Labels: Size: S

#746 build: Change rust toolchain version from nightly to stable
  .github/actions/setup-builder/action.yaml
  .github/workflows/apidoc.yml
  rust-toolchain.toml
  rustfmt.toml
Labels: size/xs

#750 test: Add test cases
  Cargo.lock
  config/journal-server.toml
  config/mqtt-server.toml
  config/placement-center.toml
  example/mqtt-cluster/journal-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  src/common/base/src/config/default_journal_server.rs
  src/common/base/src/config/default_placement_center.rs
  src/common/base/src/config/journal_server.rs
  src/common/base/src/config/placement_center.rs
  src/common/base/src/error/common.rs
  src/journal-client/Cargo.toml
  src/journal-client/src/async_writer.rs
  src/journal-client/src/cache.rs
  src/journal-client/src/client.rs
  src/journal-client/src/connection.rs
  src/journal-client/src/consts.rs
  src/journal-client/src/error.rs
  src/journal-client/src/lib.rs
  src/journal-client/src/service.rs
  src/journal-server/src/core/cluster.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/write.rs
  src/journal-server/src/server/grpc/server.rs
  src/journal-server/src/server/tcp/server.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/server/http/server.rs
  src/storage-adapter/src/journal/mod.rs
  tests/tests/journal_client/client_test.rs
  tests/tests/journal_client/common.rs
  tests/tests/journal_client/mod.rs
Labels: Size: L

#755 build: Change rust toochain to stable version
  .pre-commit-config.yaml
  docs/images/WechatGroup.jpg
  rust-toolchain.toml
  rustfmt.toml
  tests/tests/journal_client/client_test.rs
Labels: Size: S

#751 ci: Enable auto label assignment for PRs and issues
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/subtask.yml
  .github/ISSUE_TEMPLATE/umbrella.yml
  .github/labeler-config.yml
  .github/workflows/pr-issue-labeler.yml
  docs/en/ContributionGuide/GitHub-Contribution-Guide.md
  docs/images/GithubContributionGuide-1.png
  docs/images/GithubContributionGuide-2.png
  docs/images/GithubContributionGuide-3.png
  docs/images/GithubContributionGuide-4.png
  docs/images/GithubContributionGuide-5.png
  docs/images/doc-image10.png
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
Labels: Size: M

#757 refactor: Replace CommonError in mqtt-broker with MqttBrokerError
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/pkid.rs
  src/mqtt-broker/src/handler/session.rs
Labels: Size: S, kind:refactor

#749 refactor: refactor the user-related commands in the cli-command .
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/QuickGuide/Easy-Start.md
  docs/zh/QuickGuide/Easy-Start.md
  src/cli-command/src/mqtt.rs
  src/cli-command/src/placement.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
Labels: Size: M, kind:refactor

#771 chore: replace macro with the expanded code
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/raft/typeconfig.rs
Labels: Size: S, kind:chore

#770 test: Refine your test cases
  docs/zh/ContributionGuide/ContributingCode/Build-Develop-Env.md
  src/journal-client/tests/client_test.rs
  src/journal-server/src/core/segment_meta.rs
  src/journal-server/src/core/segment_status.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/tag.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/segment/scroll.rs
  src/journal-server/src/segment/write.rs
  src/journal-server/tests/mod.rs
  src/placement-center/src/journal/services/segment.rs
  tests/tests/journal_client/client_test.rs
  tests/tests/journal_client/mod.rs
  tests/tests/journal_client/segment_status_test.rs
Labels: Size: M, kind:test

#772 feat: Implement StorageAdapter for MemoryStorageAdapter
  src/storage-adapter/src/memory/mod.rs
Labels: kind:feat, Size: S

#774 feat: Add ShardConfig function
  config/journal-server.toml
  docs/en/ContributionGuide/ContributingCode/Build-Develop-Env.md
  src/common/base/src/config/default_journal_server.rs
  src/common/base/src/config/journal_server.rs
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/journal/shard.rs
  src/grpc-clients/src/placement/mod.rs
  src/grpc-clients/tests/placement/journal/segment.rs
  src/grpc-clients/tests/placement/journal/shard.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/core/cluster_config.rs
  src/journal-server/src/core/error.rs
  src/journal-server/src/core/notification.rs
  src/journal-server/src/core/segment.rs
  src/journal-server/src/core/segment_meta.rs
  src/journal-server/src/core/segment_status.rs
  src/journal-server/src/core/shard.rs
  src/journal-server/src/core/test.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/shard.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/scroll.rs
  src/journal-server/src/segment/write.rs
  src/placement-center/src/journal/services/segment.rs
  src/placement-center/src/journal/services/shard.rs
  src/protocol/src/placement_center/proto/journal.proto
  tests/tests/journal_client/mod.rs
  tests/tests/journal_client/segment_scroll.rs
  tests/tests/journal_server/data_test.rs
  tests/tests/place_server/grpc_clients_test.rs
Labels: kind:feat, Size: L

#780 doc: Fixing documentation errors
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/QuickGuide/Build.md
Labels: Size: S

#781 feat: add cli-command yaml to k8s-dev
  Dockerfile
  example/test-network-k8s/kube/cli-command.yaml
  example/test-network-k8s/kube/mqtt-server.yaml
  example/test-network-k8s/network.sh
  example/test-network-k8s/scripts/docker.sh
  example/test-network-k8s/scripts/kind.sh
  example/test-network-k8s/scripts/robustmq.sh
Labels: kind:feat, Size: S

#783 docs: integrate metrics module examples
  docs/.design/logic/Integrate the metrics module.md
  docs/.design/observability/metrics.md
Labels: kind:docs, Size: M

#785 docs: More detailed docker and k8s documentation
  docs/en/QuickGuide/Run-Docker-Mode.md
  docs/en/QuickGuide/Run-K8S-Mode.md
  docs/zh/QuickGuide/Run-Docker-Mode.md
  docs/zh/QuickGuide/Run-K8S-Mode.md
  example/test-network-docker/compose/compose-test-net.yaml
Labels: kind:docs, Size: M

#786 chore: update a picture for wechatGroup
  docs/images/WechatGroup.jpg
Labels: kind:chore

#789 chore: fix picture do not update
  docs/images/WechatGroup.jpg
Labels: size/xs, kind:chore

#790 feat: ingrate metric named 'client_connection'
  Cargo.lock
  Cargo.toml
  docs/.design/observability/metrics.md
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/observability/metrics/event_metrics.rs
  src/mqtt-broker/src/observability/metrics/events.rs
  src/mqtt-broker/src/observability/metrics/mod.rs
Labels: kind:feat, Size: M

#791 docs: add a tips for readme.md
  README.md
Labels: kind:docs, size/xs

#773 feat: rocksdb adpater implementation
  docs/.design/storage-adapter/rocksdb.md
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/rocksdb/mod.rs
Labels: kind:feat, Size: XL

#795 feat: add prost validations for grpc methods
  Cargo.lock
  Cargo.toml
  src/cli-command/src/mqtt.rs
  src/journal-server/src/segment/read.rs
  src/placement-center/Cargo.toml
  src/placement-center/src/server/grpc/service_inner.rs
  src/protocol/Cargo.toml
  src/protocol/build.rs
  src/protocol/src/placement_center/proto/inner.proto
  src/protocol/src/prost_validation_types/proto/validate/validate.proto
Labels: kind:feat, Size: L

#799 docs: upadte readme.md
  README.md
  docs/images/WechatGroup.jpg
  docs/images/WechatGroup.png
Labels: kind:docs, size/xs

#802 docs: fix broken link in readme
  README.md
Labels: kind:docs, Size: S

#782 feat: impl StorageAdapter for MySQL
  docs/.design/storage-adapter/mysql.md
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/mysql/mod.rs
  src/storage-adapter/src/mysql/schema.rs
  src/storage-adapter/src/mysql/sql.sql
  src/storage-adapter/src/storage.rs
Labels: kind:feat, Size: XL

#803 perf: Create one write handle for each namespace + shard
  src/storage-adapter/src/rocksdb/mod.rs
Labels: Size: S

#812 docs: add star history graph in README.md
  README.md
Labels: kind:docs, Size: S

#805 fix: fix mysql offset bug
  Cargo.lock
  src/storage-adapter/Cargo.toml
  src/storage-adapter/src/mysql/mod.rs
Labels: kind:bug, Size: M

#797 feat: add connection_jitter
  config/log-config/mqtt-log4rs.yaml
  docs/.design/logic/flapping-detect.md
  docs/.design/storage-adapter/rocksdb.md
  docs/.design/user-draft/flapping-detect.md
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/base/src/enum_type/mod.rs
  src/common/base/src/enum_type/sort_type.rs
  src/common/base/src/enum_type/time_unit_enum.rs
  src/common/base/src/tools.rs
  src/common/metadata-struct/src/mqtt/cluster.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/mod.rs
  src/mqtt-broker/src/handler/cluster_config.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/flapping_detect.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/validator.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/observability/metrics/event_metrics.rs
  src/mqtt-broker/src/observability/slow/sub.rs
  src/mqtt-broker/src/security/acl/metadata.rs
  src/mqtt-broker/src/security/acl/mod.rs
  src/mqtt-broker/src/security/mod.rs
  src/mqtt-broker/src/security/mysql/schema.rs
  src/mqtt-broker/src/server/grpc/admin/services.rs
  src/mqtt-broker/src/server/http/server.rs
  src/mqtt-broker/src/server/tcp/tcp_server.rs
  src/mqtt-broker/src/subscribe/sub_exclusive.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  tests/tests/mqtt_client/flapping_detect_test.rs
  tests/tests/mqtt_client/mod.rs
  tests/tests/mqtt_client/slow_sub_test.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/connect34_test.rs
  tests/tests/mqtt_protocol/connect_suite.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/req_resp_test.rs
Labels: kind:feat, Size: XL

#811 chore: store shard config in rocksdb
  src/storage-adapter/src/rocksdb/mod.rs
Labels: Size: S, kind:chore

#815 chore: Add favicon.ico to RobustMQ
  docs/.vitepress/src/head.mts
  docs/public/favicon.ico
Labels: size/xs, kind:chore

#817 doc: Update the Readme.md
  README.md
Labels: Size: M

#818 perf: improve throughput for rocksdb
  src/storage-adapter/src/rocksdb/mod.rs
Labels: Size: M

#819 docs: add comments under src/journal-server and src/common/metadata-struct
  src/common/metadata-struct/src/journal/segment.rs
  src/common/metadata-struct/src/journal/segment_meta.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/segment/file.rs
  src/journal-server/src/segment/manager.rs
  src/journal-server/src/segment/mod.rs
  src/journal-server/src/segment/read.rs
  src/journal-server/src/segment/scroll.rs
  src/journal-server/src/segment/write.rs
Labels: kind:docs, Size: S
