Repository robustmq/robustmq, pull requests merged in 2025-03, with the labels that each got.

#893 chore: no need to send update connector request to PC during GC
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/lib.rs
Labels: Size: S, kind:chore

#894 feat: MQTT Broker supports schema
  Cargo.lock
  src/common/metadata-struct/src/schema.rs
  src/grpc-clients/src/placement/inner/call.rs
  src/grpc-clients/src/placement/inner/mod.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/server/tcp/server.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/mod.rs
  src/placement-center/src/core/schema.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  src/placement-center/src/route/common.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/mod.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/placement-center/src/storage/keys.rs
  src/placement-center/src/storage/placement/mod.rs
  src/placement-center/src/storage/placement/schema.rs
  src/protocol/src/broker_mqtt/proto/inner.proto
  src/protocol/src/placement_center/proto/inner.proto
  src/schema-register/src/schema.rs
Labels: kind:feat, Size: XL

#895 feat: Add protofish tests
  Cargo.lock
  Cargo.toml
  src/schema-register/Cargo.toml
  src/schema-register/src/protobuf.rs
Labels: kind:feat, Size: M

#897 test: Add schema-related test cases
  docs/images/WechatGroup
  src/schema-register/src/schema.rs
Labels: kind:test

#898 feat: Add Mqtt-broker schema Admin GRPC and CLI
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/metadata-struct/src/schema.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/placement/mqtt/mod.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_schema_test.rs
  src/mqtt-broker/src/handler/cache_update.rs
  src/mqtt-broker/src/handler/error.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/storage/mod.rs
  src/mqtt-broker/src/storage/schema.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  src/schema-register/src/schema.rs
Labels: kind:feat, Size: XL

#902 feat: add validation for protobuf schema
  src/schema-register/src/protobuf.rs
Labels: kind:feat, Size: M

#903 fix: Fix duplicate test cases
  src/schema-register/src/schema.rs
Labels: kind:bug, Size: M

#906 refactor: refactor the list_connectors method.
  src/cli-command/src/mqtt.rs
Labels: Size: S, kind:refactor

#905 test: complete CRUD test for connector
  src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
  src/mqtt-broker/src/bridge/request.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/placement-center/src/mqtt/connector/request.rs
Labels: Size: M, kind:test

#907 test: update schema test cases
  src/cli-command/src/mqtt.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_schema_test.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/storage/schema.rs
Labels: Size: M, kind:test

#911 refactor: refactor the list_connections method.
  src/cli-command/src/mqtt.rs
Labels: Size: S, kind:refactor

#910 feat: connector now supports Kafka plugin
  Cargo.lock
  Cargo.toml
  src/common/metadata-struct/src/mqtt/bridge/config_kafka.rs
  src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/bridge/kafka/mod.rs
  src/mqtt-broker/src/handler/error.rs
Labels: kind:feat, Size: S

#915 feat: Improve documentation & Add GRPC intercepters
  Cargo.lock
  Cargo.toml
  docs/.design/plan/mqtt-all-feature.md
  docs/.design/plan/mqtt-stable-to-do.md
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-MQTT/GrpcAdmin.md
  docs/zh/RobustMQ-MQTT/GrpcAdmin.md
  src/common/base/src/tools.rs
  src/placement-center/Cargo.toml
  src/placement-center/src/lib.rs
  src/placement-center/src/raft/leadership.rs
  src/placement-center/src/server/grpc/mod.rs
  src/placement-center/src/server/grpc/server.rs
  src/placement-center/src/server/grpc/service_kv.rs
Labels: kind:feat, Size: XL

#917 docs: Fix document content errors
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
Labels: kind:docs

#918 docs: Fix document content errors
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
Labels: kind:docs, size/xs

#919 docs: Fix document content errors
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
Labels: kind:docs

#920 docs: Fix document content errors
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
Labels: kind:docs

#921 docs: Fix document content errors
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
Labels: kind:docs, Size: S

#922 docs: Documentation that complements MQTT
  Cargo.lock
  Cargo.toml
  docs/.DS_Store
  docs/en/RobustMQ-MQTT/Overview.md
  docs/en/RobustMQ-MQTT/RetainMessage.md
  docs/en/RobustMQ-MQTT/SharedSubscription.md
  docs/en/RobustMQ-MQTT/SystemArchitecture.md
  docs/images/storage-adapter.png
  docs/zh/Architect/Placement-Center.md
  docs/zh/Architect/Storage-Adapter.md
  docs/zh/RobustMQ-MQTT/Overview.md
  docs/zh/RobustMQ-MQTT/RetainMessage.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
  docs/zh/RobustMQ-MQTT/SystemArchitecture.md
  docs/zh/RobustMQ-MQTT/WillMessage.md
  src/placement-center/Cargo.toml
  src/placement-center/src/core/metrics.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/mqtt/services/acl.rs
  src/placement-center/src/server/grpc/server.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/placement-center/src/server/http/index.rs
  src/placement-center/src/server/http/mod.rs
  src/placement-center/src/server/http/server.rs
  src/placement-center/src/server/mod.rs
Labels: kind:docs, Size: M

#923 fix: if schema to be updated exists for update_schem_req() function. close #909
  src/placement-center/src/core/schema.rs
Labels: kind:bug, size/xs

#924 feat: Message format verification is performed based on CRC
  Cargo.lock
  Cargo.toml
  config/log-config/mqtt-log4rs.yaml
  config/log-config/place-log4rs.yaml
  config/mqtt-server.toml
  docs/.DS_Store
  docs/.design/plan/mqtt-stable-to-do.md
  docs/zh/Architect/Storage-Adapter.md
  src/common/base/Cargo.toml
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/common.rs
  src/common/base/src/config/default_journal_server.rs
  src/common/base/src/config/default_mqtt.rs
  src/common/base/src/config/journal_server.rs
  src/common/base/src/error/common.rs
  src/common/base/src/utils/crc.rs
  src/common/base/src/utils/mod.rs
  src/common/metadata-struct/Cargo.toml
  src/common/metadata-struct/src/adapter/record.rs
  src/common/metadata-struct/src/mqtt/node_extend.rs
  src/journal-client/src/client.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/server/http/mod.rs
  src/mqtt-broker/src/server/http/prometheus.rs
  src/mqtt-broker/src/server/http/publish.rs
  src/mqtt-broker/src/server/http/server.rs
  src/mqtt-broker/src/server/mod.rs
  src/mqtt-broker/src/storage/cluster.rs
  src/mqtt-broker/src/storage/message.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/schema.rs
  src/placement-center/src/server/grpc/service_inner.rs
  src/storage-adapter/src/minio/mod.rs
  src/storage-adapter/src/mysql/mod.rs
  src/storage-adapter/src/rocksdb/mod.rs
Labels: kind:feat, Size: L

#927 doc: Improve the Quickstart documentation
  docs/.DS_Store
  docs/.vitepress/src/sidebars/zh.mts
  docs/zh/QuickGuide/Overview.md
  docs/zh/QuickGuide/Run-Cluster-Mode.md
  docs/zh/QuickGuide/Run-Standalone-Mode.md
  docs/zh/QuickGuide/mqtt/Build.md
  docs/zh/QuickGuide/mqtt/MQTT-test.md
  docs/zh/QuickGuide/mqtt/Run-Cluster-Mode.md
  docs/zh/QuickGuide/mqtt/Run-Docker-Mode.md
  docs/zh/QuickGuide/mqtt/Run-K8S-Mode.md
  docs/zh/QuickGuide/mqtt/Run-Standalone-Mode.md
  docs/zh/RobustMQ-MQTT/SharedSubscription.md
  example/mqtt-cluster/mqtt-server/node-1.toml
  example/mqtt-cluster/mqtt-server/node-2.toml
  example/mqtt-cluster/mqtt-server/node-3.toml
  example/mqtt-cluster/placement-center/node-1.toml
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  makefile
  scripts/build-release.sh
Labels: Size: M

#928 doc: Fixed document linking issues
  docs/zh/QuickGuide/mqtt/Run-Cluster-Mode.md
Labels: size/xs

#930 docs: Improve the release planning documentation
  docs/en/QuickGuide/mqtt/Run-Docker-Mode.md
  docs/en/QuickGuide/mqtt/Run-K8S-Mode.md
Labels: kind:docs

#932 feat: Implement StorageAdapter for placement center
  scripts/place-ig-test.sh
  src/grpc-clients/src/placement/kv/call.rs
  src/grpc-clients/src/placement/kv/mod.rs
  src/placement-center/src/server/grpc/service_kv.rs
  src/placement-center/src/storage/placement/kv.rs
  src/protocol/src/placement_center/proto/kv.proto
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/placement/mod.rs
Labels: kind:feat, Size: XL

#933 fix: Fix pipeline bugs
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  example/test-config/journal.toml
  example/test-config/mqtt.toml
  example/test-config/place.toml
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
Labels: kind:bug, Size: M

#934 fix: fixed placement storage adapter test
  scripts/unit-test.sh
  src/storage-adapter/src/placement/mod.rs
Labels: kind:bug, Size: S

#939 ci: add code coverage ci workflow
  .github/workflows/unit-test.yml
Labels: Size: S, kind:ci

#935 feat: Fix mqtt test case failures
  config/journal-server.toml
  config/log-config/journal-log4rs.yaml
  config/log-config/mqtt-log4rs.yaml
  config/placement-center.toml
  src/common/base/src/config/placement_center.rs
  src/delay-message/src/lib.rs
  src/journal-server/src/server/tcp/response.rs
  src/mqtt-broker/src/handler/retain.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/subscribe/share_leader_push.rs
  tests/tests/mqtt_protocol/mod.rs
Labels: kind:feat, Size: M, kind:test

#936 fix(rdkafka): Fixed Win compilation issues
  Cargo.lock
  Cargo.toml
Labels: kind:bug, size/xs

#941 docs: Update Constribution Guide docs in Chinese
  docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
  docs/zh/ContributionGuide/Pull-Request-Example.md
Labels: kind:docs, Size: M

#943 style: prevent file too large
  docs/images/WechatGroup.png
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/server/grpc/admin.rs
Labels: Size: L, kind:style

#944 test: mqtt broker Test Case optimization
  Cargo.lock
  Cargo.toml
  docs/en/Architect/Overview.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/zh/Architect/Overview.md
  docs/zh/OverView/What-is-RobustMQ.md
  jn-1.log
  pc-1.log
  src/cmd/Cargo.toml
  src/common/metadata-struct/src/mqtt/session.rs
  src/common/rocksdb-engine/src/engine.rs
  src/common/rocksdb-engine/src/lib.rs
  src/common/rocksdb-engine/src/warp.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_session_test.rs
  src/journal-server/src/index/build.rs
  src/journal-server/src/index/offset.rs
  src/journal-server/src/index/time.rs
  src/mqtt-broker/src/storage/session.rs
  src/placement-center/src/mqtt/controller/message_expire.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  src/placement-center/src/mqtt/services/session.rs
  src/placement-center/src/raft/store/state_machine_store.rs
  src/placement-center/src/route/data.rs
  src/placement-center/src/route/mqtt.rs
  src/placement-center/src/storage/journal/segment.rs
  src/placement-center/src/storage/journal/segment_meta.rs
  src/placement-center/src/storage/journal/shard.rs
  src/placement-center/src/storage/mqtt/acl.rs
  src/placement-center/src/storage/mqtt/blacklist.rs
  src/placement-center/src/storage/mqtt/connector.rs
  src/placement-center/src/storage/mqtt/lastwill.rs
  src/placement-center/src/storage/mqtt/session.rs
  src/placement-center/src/storage/mqtt/subscribe.rs
  src/placement-center/src/storage/mqtt/topic.rs
  src/placement-center/src/storage/mqtt/user.rs
  src/placement-center/src/storage/placement/cluster.rs
  src/placement-center/src/storage/placement/config.rs
  src/placement-center/src/storage/placement/kv.rs
  src/placement-center/src/storage/placement/node.rs
  src/placement-center/src/storage/placement/offset.rs
  src/placement-center/src/storage/placement/schema.rs
  src/protocol/src/placement_center/proto/mqtt.proto
Labels: Size: M, kind:test

#946 style: Remove duplicate copyrights in multiple files
  src/cmd/tests/mod.rs
  src/common/base/src/config/broker_mqtt.rs
  src/common/base/src/config/journal_server.rs
  src/common/base/src/config/placement_center.rs
  src/common/base/src/error/common.rs
  src/common/base/src/http_error.rs
  src/common/base/src/runtime.rs
  src/common/base/src/version/logo.rs
  src/common/base/tests/mod.rs
  src/placement-center/src/storage/mod.rs
Labels: Size: M, kind:style

#947 docs: Add robustmq to introduce documentation
  docs/en/Architect/Overview.md
  docs/en/Architect/Storage-Adapter.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/en/OverView/Why-RobustMQ.md
  docs/zh/OverView/What-is-RobustMQ.md
  docs/zh/OverView/Why-RobustMQ.md
  src/cmd/src/mqtt-server/server.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/placement-center/src/core/controller.rs
  src/placement-center/src/core/heartbeat.rs
Labels: kind:docs, Size: M

#949 refactor: Optimize the makefile and release-build scripts
  makefile
  scripts/build-release.sh
Labels: Size: M, kind:refactor

#948 refactor: remove calc_init_node function and update log config path
  example/mqtt-cluster/placement-center/node-2.toml
  example/mqtt-cluster/placement-center/node-3.toml
  src/placement-center/src/raft/raft_node.rs
Labels: Size: S, kind:refactor

#953 docs: Update MQTT build documentation for multiple platforms
  docs/en/QuickGuide/mqtt/Build.md
  docs/zh/QuickGuide/mqtt/Build.md
Labels: kind:docs, Size: M

#952 docs: Update README.md for clarity and links
  README.md
Labels: kind:docs, Size: S

#954 test(placement-center): add unit tests for KvStorage
  Cargo.lock
  Cargo.toml
  src/placement-center/Cargo.toml
  src/placement-center/src/storage/placement/kv.rs
Labels: Size: S, kind:test

#951 ci: support ci coverage
  .github/workflows/unit-test.yml
  README.md
Labels: Size: S, kind:ci

#957 fix: Use POSIX compatible array syntax
  Cargo.lock
  scripts/build-release.sh
Labels: kind:bug, size/xs

#960 test(node): add unit tests for NodeStorage
  src/placement-center/src/storage/placement/node.rs
Labels: Size: S, kind:test

#964 feat: placement list shard
  src/storage-adapter/src/placement/mod.rs
Labels: kind:feat, Size: S

#961 feat: rocksdb support list shard
  src/storage-adapter/src/rocksdb/mod.rs
  src/storage-adapter/src/storage.rs
Labels: kind:feat, Size: S

#958 fix: make build bug fix
  Cargo.toml
  scripts/build-release.sh
Labels: kind:bug, size/xs

#972 test: check read_config and fixed leaky tests
  src/storage-adapter/src/rocksdb/mod.rs
Labels: Size: S, kind:test

#976 style:Extract auto_subscribe Function to Reduce File Size(#970)
  src/placement-center/src/mqtt/services/subscribe.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
Labels: Size: S, kind:style

#977 test: add MQTT acl storage test
  src/placement-center/src/storage/mqtt/acl.rs
Labels: Size: M, kind:test

#974 feat: mysql list shard
  src/storage-adapter/src/mysql/mod.rs
Labels: kind:feat, Size: S

#971 fix:Check whether the schema to be created already exists in create_schema_req #908
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/schema.rs
  src/placement-center/src/server/grpc/service_inner.rs
Labels: kind:bug, Size: S

#973 fix: Optimizing subscription logic
  Cargo.lock
  config/log-config/mqtt-log4rs.yaml
  scripts/mqtt-ig-test.sh
  src/common/rocksdb-engine/Cargo.toml
  src/common/rocksdb-engine/src/engine.rs
  src/common/rocksdb-engine/src/lib.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/subscribe/exclusive_push.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  tests/tests/mqtt_protocol/topic_rewrite_rule_test.rs
Labels: kind:bug, Size: M

#982 test: Rewrite mqtt protocol test cases
  config/log-config/mqtt-log4rs.yaml
  src/mqtt-broker/src/handler/connection.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/server/quic/response.rs
  src/mqtt-broker/src/server/tcp/response.rs
  src/mqtt-broker/src/subscribe/exclusive_push.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/connect34_test.rs
  tests/tests/mqtt_protocol/connect5_test.rs
  tests/tests/mqtt_protocol/connect_suite.rs
  tests/tests/mqtt_protocol/connect_test.rs
  tests/tests/mqtt_protocol/flapping_detect_test.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/sub_options_test.rs
Labels: Size: XL, kind:test

#985 test: add placement cluster test
  src/placement-center/src/storage/placement/cluster.rs
Labels: Size: S, kind:test

#987 feat: Journal server supports `list_shard`
  src/journal-client/src/client.rs
  src/journal-client/src/error.rs
  src/journal-client/src/service.rs
  src/journal-server/src/core/cache.rs
  src/journal-server/src/handler/command.rs
  src/journal-server/src/handler/shard.rs
  src/protocol/src/journal_server/codec.rs
  src/protocol/src/journal_server/proto/engine.proto
  src/storage-adapter/src/journal/mod.rs
Labels: kind:feat, Size: M

#984 fix: POSIX compatible build script
  .gitattributes
  docs/en/QuickGuide/mqtt/MQTT-test.md
  docs/en/QuickGuide/mqtt/Run-Cluster-Mode.md
  docs/en/QuickGuide/mqtt/Run-Standalone-Mode.md
  docs/en/RobustMQ-Command/Mqtt-Broker.md
  docs/en/RobustMQ-Command/Overview.md
  docs/en/RobustMQ-Command/Placement-Center.md
  docs/zh/QuickGuide/mqtt/Build.md
  docs/zh/QuickGuide/mqtt/MQTT-test.md
  docs/zh/QuickGuide/mqtt/Run-Cluster-Mode.md
  docs/zh/QuickGuide/mqtt/Run-Standalone-Mode.md
  docs/zh/RobustMQ-Command/Mqtt-Broker.md
  docs/zh/RobustMQ-Command/Overview.md
  scripts/build-release.sh
Labels: kind:bug, Size: M

#965 style: Organize gRPC interfaces
  .github/workflows/unit-test.yml
  .gitignore
  README.md
  docs/en/Architect/Overview.md
  docs/en/Architect/Storage-Adapter.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/en/OverView/Why-RobustMQ.md
  docs/zh/Architect/Overview.md
  docs/zh/OverView/What-is-RobustMQ.md
  docs/zh/OverView/Why-RobustMQ.md
  src/common/base/src/version/logo.rs
  src/grpc-clients/tests/placement/mqtt/mqtt_topic_test.rs
  src/mqtt-broker/src/admin/acl.rs
  src/mqtt-broker/src/admin/connector.rs
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/admin/subscribe.rs
  src/mqtt-broker/src/admin/topic.rs
  src/mqtt-broker/src/admin/user.rs
  src/mqtt-broker/src/bridge/mod.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/storage/schema.rs
  src/placement-center/src/core/error.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/mqtt/cache.rs
  src/placement-center/src/mqtt/connector/mod.rs
  src/placement-center/src/mqtt/connector/request.rs
  src/placement-center/src/mqtt/services/acl.rs
  src/placement-center/src/mqtt/services/connector.rs
  src/placement-center/src/mqtt/services/mod.rs
  src/placement-center/src/mqtt/services/session.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/mqtt/services/subscribe.rs
  src/placement-center/src/mqtt/services/topic.rs
  src/placement-center/src/mqtt/services/user.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  tests/tests/mqtt_protocol/sub_options_test.rs
Labels: Size: XL, kind:style

#989 refactor(protocol): split proto file to independent repo and remove t…
  Cargo.lock
  Cargo.toml
  README.md
  docs/images/WechatGroup.jpg
  docs/images/WechatGroup.png
  src/protocol/Cargo.toml
  src/protocol/build.rs
  src/protocol/src/broker_mqtt/proto/admin.proto
  src/protocol/src/broker_mqtt/proto/inner.proto
  src/protocol/src/journal_server/proto/admin.proto
  src/protocol/src/journal_server/proto/engine.proto
  src/protocol/src/journal_server/proto/inner.proto
  src/protocol/src/journal_server/proto/record.proto
  src/protocol/src/placement_center/proto/inner.proto
  src/protocol/src/placement_center/proto/journal.proto
  src/protocol/src/placement_center/proto/kv.proto
  src/protocol/src/placement_center/proto/mqtt.proto
  src/protocol/src/placement_center/proto/openraft.proto
  src/protocol/src/prost_validation_types/proto/validate/validate.proto
Labels: Size: XL, kind:refactor

#988 feat: Optimize MQTT Protocol test cases
  .github/workflows/journal-ig-test.yml
  .github/workflows/mqtt-ig-test.yml
  .github/workflows/place-ig-test.yml
  .github/workflows/unit-test.yml
  codecheck.sh
  example/test-config/journal.toml
  example/test-config/mqtt.toml
  example/test-config/place.toml
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/placement-center/src/journal/controller/mod.rs
  src/placement-center/src/mqtt/controller/call_broker.rs
  src/placement-center/src/mqtt/controller/mod.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/connect_packet_size_test.rs
  tests/tests/mqtt_protocol/lastwill_message_test.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/qos_test.rs
  tests/tests/mqtt_protocol/retain_message_test.rs
  tests/tests/mqtt_protocol/sub34_qos_test.rs
  tests/tests/mqtt_protocol/sub5_qos_test.rs
  tests/tests/mqtt_protocol/topic_alias_test.rs
  tests/tests/mqtt_protocol/trace_test.rs
  tests/tests/mqtt_protocol/user_properties_test.rs
  tests/tests/mqtt_protocol/ws_sub_pub_test.rs
  tests/tests/mqtt_protocol/wss_sub_pub_test.rs
Labels: kind:feat, Size: XL

#993 test: Add unit test for MqttSubscribeStorage
  src/common/metadata-struct/src/mqtt/subscribe_data.rs
  src/placement-center/src/storage/mqtt/subscribe.rs
  src/protocol/src/mqtt/common.rs
Labels: kind:feat, Size: M, kind:test

#994 test: Add unit test for ResourceConfigStorage
  src/placement-center/src/storage/placement/config.rs
Labels: Size: S, kind:test

#995 feat: Delete stale ids in mysql auto increment tables
  src/storage-adapter/src/mysql/mod.rs
Labels: kind:feat, Size: S

#998 test: add journal segment unit test
  src/placement-center/src/storage/journal/segment.rs
Labels: Size: M, kind:test

#1001 test: Add unit test for IdempotentStorage
  src/placement-center/src/storage/placement/idempotent.rs
Labels: Size: S, kind:test

#1005 feat: enable journal-server and broker-mtqq grpc-web
  Cargo.lock
  src/journal-server/Cargo.toml
  src/journal-server/src/server/grpc/server.rs
  src/mqtt-broker/Cargo.toml
  src/mqtt-broker/src/server/grpc/server.rs
Labels: kind:feat, Size: S

#1000 test: Add unit test for OffsetStorage
  src/placement-center/src/storage/placement/offset.rs
Labels: Size: S, kind:test

#992 test: Optimize MQTT Protocol functional integration tests
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  src/mqtt-broker/src/admin/topic.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/placement-center/src/mqtt/services/topic.rs
  tests/tests/mqtt_protocol/auth_test.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/connect5_test.rs
  tests/tests/mqtt_protocol/connect_packet_size_test.rs
  tests/tests/mqtt_protocol/connect_test.rs
  tests/tests/mqtt_protocol/keep_alive_test.rs
  tests/tests/mqtt_protocol/lastwill_message_test.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/permission34_test.rs
  tests/tests/mqtt_protocol/permission5_test.rs
  tests/tests/mqtt_protocol/qos_test.rs
  tests/tests/mqtt_protocol/retain_message_test.rs
  tests/tests/mqtt_protocol/sub_exclusive_test.rs
  tests/tests/mqtt_protocol/topic_alias_test.rs
  tests/tests/mqtt_protocol/topic_rewrite_rule_test.rs
  tests/tests/mqtt_protocol/user_properties_test.rs
Labels: Size: XL, kind:test

#1013 fix: fix `mqtt_share_sub_test` in place-ig-test
  src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs
Labels: kind:bug, size/xs

#1012 fix: fix resource busy bug when running multiple rocksdb instances concurrently
  Cargo.lock
  src/common/rocksdb-engine/Cargo.toml
  src/common/rocksdb-engine/src/engine.rs
Labels: kind:bug, Size: S

#1014 test: Add unit test for JournalShard 2
  src/placement-center/src/storage/journal/shard.rs
Labels: Size: S, kind:test

#1015 style: remove deprecated method: get_current_millisecond_timestamp
  src/common/base/src/utils/mod.rs
  src/common/base/src/utils/time_util.rs
  src/placement-center/src/route/mqtt.rs
Labels: Size: S, kind:style

#1006 ci: Optimize CI for integration tests
  .github/workflows/journal-ig-test.yml
  .github/workflows/mqtt-ig-test.yml
  .github/workflows/place-ig-test.yml
  .github/workflows/unit-test.yml
  Cargo.lock
  makefile
  scripts/journal-ig-test.sh
  scripts/mqtt-ig-test.sh
  scripts/place-ig-test.sh
  src/common/base/Cargo.toml
  src/common/base/src/config/placement_center.rs
  src/common/base/src/utils/file_utils.rs
  src/common/rocksdb-engine/src/lib.rs
  src/placement-center/src/mqtt/controller/message_expire.rs
  src/placement-center/src/mqtt/controller/session_expire.rs
  src/placement-center/src/mqtt/services/share_sub.rs
  src/placement-center/src/route/common.rs
  src/placement-center/src/storage/mqtt/acl.rs
  src/placement-center/src/storage/mqtt/connector.rs
  src/placement-center/src/storage/mqtt/lastwill.rs
  src/placement-center/src/storage/mqtt/session.rs
  src/placement-center/src/storage/mqtt/subscribe.rs
  src/placement-center/src/storage/mqtt/topic.rs
  src/placement-center/src/storage/mqtt/user.rs
  tests/tests/mqtt_protocol/mod.rs
  tests/tests/mqtt_protocol/req_resp_test.rs
  tests/tests/mqtt_protocol/sub_identifier_test.rs
Labels: Size: L, kind:ci

#1016 fix: fix recover snapshot serialization bug
  src/common/rocksdb-engine/src/lib.rs
  src/placement-center/src/route/mod.rs
Labels: kind:bug, Size: S

#1017 docs: Update Journal Server documentation for clarity and consistency
  docs/en/Architect/Journal-Server.md
Labels: kind:docs, size/xs

#1023 test:Add unit test for segment_meta.rs
  src/placement-center/src/storage/journal/segment_meta.rs
Labels: Size: M, kind:test

#1021 feat: Robustctl MQTT Command support Acl and Blacklist
  Cargo.lock
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/metadata-struct/src/acl/mqtt_acl.rs
Labels: kind:feat, Size: M

#1025 test: test mqtt5 subscribe options
  .github/workflows/mqtt-ig-test.yml
  src/mqtt-broker/src/handler/offline_message.rs
  src/mqtt-broker/src/handler/subscribe.rs
  tests/tests/mqtt_protocol/common.rs
  tests/tests/mqtt_protocol/sub_options_test.rs
Labels: Size: L, kind:test

#1022 test: Add unit test and documents for mqtt topic rewrite
  docs/en/RobustMQ-MQTT/TopicRewrite.md
  src/mqtt-broker/src/handler/topic_rewrite.rs
  src/mqtt-broker/src/subscribe/sub_common.rs
Labels: Size: M, kind:test

#1028 refactor: move schema to admin directory
  src/mqtt-broker/src/admin/mod.rs
  src/mqtt-broker/src/admin/schema.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/storage/mod.rs
Labels: Size: S, kind:refactor
