Repository robustmq/robustmq, pull requests merged in 2025-07, with the labels that each got.

#1205 refactor: refactor journal server grpc interface function
  src/grpc-clients/tests/placement/mqtt/cluster_test.rs
  src/journal-server/src/admin/mod.rs
  src/journal-server/src/admin/services.rs
  src/journal-server/src/inner/mod.rs
  src/journal-server/src/inner/services.rs
  src/journal-server/src/lib.rs
  src/journal-server/src/server/grpc/admin.rs
  src/journal-server/src/server/grpc/inner.rs
  src/mqtt-broker/src/admin/mod.rs
Labels: Size: L, kind:refactor

#1207 doc: Update mainstream comparison document
  docs/.vitepress/src/sidebars/zh.mts
  docs/en/OverView/Diff-MQ.md
  docs/en/OverView/Diff-iggy.md
  docs/zh/OverView/Diff-MQ.md
Labels: Size: M

#1212 style: simplified code
  src/common/base/src/utils/mod.rs
  src/common/base/src/utils/time_util.rs
  src/common/metadata-struct/src/placement/node.rs
  src/mqtt-broker/src/storage/session.rs
Labels: Size: S, kind:style

#1213 style: simplified code
  src/mqtt-broker/src/storage/cluster.rs
  src/mqtt-broker/src/storage/topic.rs
Labels: Size: S, kind:style

#1214 fix: Fix the bugs existing in the shared subscription.
  docs/.vitepress/src/sidebars/en.mts
  docs/.vitepress/src/sidebars/zh.mts
  docs/zh/OverView/Diff-iggy.md
  src/mqtt-broker/src/server/connection_manager.rs
  src/mqtt-broker/src/subscribe/manager.rs
  src/mqtt-broker/src/subscribe/push.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/placement-center/src/mqtt/services/share_sub.rs
Labels: kind:bug, Size: S, Size: M

#1234 refactor: Use Box<CommonError> to fix the result_large_err warning in clippy.
  src/journal-client/src/lib.rs
  src/journal-client/src/option.rs
Labels: kind:bug, size/xs, kind:refactor

#1193 feat:support list subscribe for mqtt-broker
  src/mqtt-broker/src/admin/subscribe.rs
  src/mqtt-broker/src/handler/sub_parse_topic.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/subscribe/manager.rs
Labels: kind:feat, Size: S

#1249 feat: Improve the time tool class. test does not perform assert judgmentsDevelop
  Cargo.lock
  Cargo.toml
  src/common/base/Cargo.toml
  src/common/base/src/utils/time_util.rs
Labels: kind:feat, Size: M

#1251 feat: Add interface related to subscription list
  Cargo.lock
  Cargo.toml
  src/cli-command/src/mqtt.rs
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
  src/common/metadata-struct/src/mqtt/subscribe_data.rs
  src/grpc-clients/src/mqtt/admin/call.rs
  src/grpc-clients/src/mqtt/admin/mod.rs
  src/mqtt-broker/src/admin/subscribe.rs
  src/mqtt-broker/src/handler/subscribe.rs
  src/mqtt-broker/src/handler/unsubscribe.rs
  src/mqtt-broker/src/server/grpc/admin.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/manager.rs
Labels: kind:feat, Size: M, Size: L

#1250 chore: replace toolchain with the tracked stable version
  .github/workflows/code-style.yml
  codecheck.sh
  rust-toolchain.toml
Labels: size/xs, kind:chore

#1257 feat: Filter logs by user specified target/path
  config/log-config/journal-tracing.toml
  config/log-config/mqtt-tracing.toml
  config/log-config/place-tracing.toml
  src/common/base/src/logging/config.rs
  src/common/base/src/logging/console.rs
  src/common/base/src/logging/filter.rs
  src/common/base/src/logging/fmt.rs
  src/common/base/src/logging/mod.rs
  src/common/base/src/logging/rolling_file.rs
  src/common/base/src/logging/tokio_console.rs
  src/robustmq-macro/src/lib.rs
Labels: kind:feat, Size: M

#1260 chore: synchronize new configuration in single-cluster and remove lint allow rules
  .github/workflows/code-style.yml
  codecheck.sh
  example/single-mqtt-cluster/journal-server/journal-tracing.toml
  example/single-mqtt-cluster/mqtt-server/mqtt-tracing.toml
  example/single-mqtt-cluster/placement-center/place-tracing.toml
Labels: Size: S, kind:chore

#1267 docs: Fix OpenMessaging typo in a few places
  docs/en/Architect/Broker-Server.md
  docs/en/OverView/What-is-RobustMQ.md
  docs/en/index.md
  docs/zh/Architect/Broker-Server.md
  docs/zh/OverView/What-is-RobustMQ.md
  docs/zh/index.md
Labels: kind:docs, Size: S

#1265 feat: Draw a very cool logo of RobustMQ using code
  src/common/base/src/version/logo.rs
Labels: kind:feat, Size: S

#1287 refactor: Optimize the writing style of StorageAdapter
  README.md
  docs/images/mqtt-start.png
  src/cmd/src/mqtt-server/server.rs
  src/common/base/src/version/logo.rs
  src/common/base/src/version/mod.rs
  src/delay-message/src/delay.rs
  src/delay-message/src/lib.rs
  src/delay-message/src/persist.rs
  src/delay-message/src/pop.rs
  src/mqtt-broker/src/admin/inner.rs
  src/mqtt-broker/src/bridge/core.rs
  src/mqtt-broker/src/bridge/file/mod.rs
  src/mqtt-broker/src/bridge/kafka/mod.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/common/types.rs
  src/mqtt-broker/src/handler/command.rs
  src/mqtt-broker/src/handler/heartbeat.rs
  src/mqtt-broker/src/handler/heatbeat.rs
  src/mqtt-broker/src/handler/keep_alive.rs
  src/mqtt-broker/src/handler/last_will.rs
  src/mqtt-broker/src/handler/mod.rs
  src/mqtt-broker/src/handler/mqtt.rs
  src/mqtt-broker/src/handler/offline_message.rs
  src/mqtt-broker/src/handler/session.rs
  src/mqtt-broker/src/handler/topic.rs
  src/mqtt-broker/src/lib.rs
  src/mqtt-broker/src/observability/mod.rs
  src/mqtt-broker/src/observability/system_topic/broker.rs
  src/mqtt-broker/src/observability/system_topic/event.rs
  src/mqtt-broker/src/observability/system_topic/mod.rs
  src/mqtt-broker/src/observability/system_topic/packet/bytes.rs
  src/mqtt-broker/src/observability/system_topic/packet/messages.rs
  src/mqtt-broker/src/observability/system_topic/packet/packets.rs
  src/mqtt-broker/src/observability/system_topic/stats/client.rs
  src/mqtt-broker/src/observability/system_topic/stats/route.rs
  src/mqtt-broker/src/observability/system_topic/stats/subscription.rs
  src/mqtt-broker/src/observability/system_topic/stats/topics.rs
  src/mqtt-broker/src/observability/system_topic/sysmon.rs
  src/mqtt-broker/src/observability/system_topic/warn.rs
  src/mqtt-broker/src/observability/warn/mod.rs
  src/mqtt-broker/src/security/auth/super_user.rs
  src/mqtt-broker/src/server/common/handler.rs
  src/mqtt-broker/src/server/grpc/inner.rs
  src/mqtt-broker/src/server/grpc/server.rs
  src/mqtt-broker/src/server/quic/server.rs
  src/mqtt-broker/src/server/server.rs
  src/mqtt-broker/src/server/tcp/v1/server.rs
  src/mqtt-broker/src/server/websocket/server.rs
  src/mqtt-broker/src/storage/message.rs
  src/mqtt-broker/src/subscribe/common.rs
  src/mqtt-broker/src/subscribe/exclusive/mod.rs
  src/mqtt-broker/src/subscribe/share/leader.rs
  src/storage-adapter/src/lib.rs
  src/storage-adapter/src/mysql/mod.rs
  src/storage-adapter/src/rocksdb/mod.rs
  src/storage-adapter/src/storage.rs
Labels: Size: XL, kind:refactor

#1289 feat: add interface about geting retain message
  Cargo.lock
  src/grpc-clients/src/placement/mqtt/call.rs
  src/grpc-clients/src/placement/mqtt/mod.rs
  src/placement-center/src/mqtt/services/topic.rs
  src/placement-center/src/server/grpc/service_mqtt.rs
Labels: kind:feat, Size: M

#1286 refactor: Security module code optimization
  src/mqtt-broker/src/security/auth/blacklist.rs
  src/mqtt-broker/src/security/auth/mod.rs
  src/mqtt-broker/src/security/mod.rs
Labels: Size: S, Size: M, kind:refactor

#1271 feat: add connections metrics for mqtt-broker
  .gitignore
  src/common/base/src/metrics/gauge.rs
  src/common/base/src/metrics/mod.rs
  src/mqtt-broker/src/common/metrics_cache.rs
  src/mqtt-broker/src/observability/metrics/server.rs
Labels: kind:feat, Size: S

#1293 fix: fix the error of executing async task outside async runtime
  src/journal-server/src/lib.rs
Labels: kind:bug, Size: S, Size: M

#1268 refactor: Version information management optimization
  config/version.ini
  scripts/build-release.sh
  src/common/base/Cargo.toml
  src/common/base/src/version/logo.rs
  src/common/base/src/version/mod.rs
Labels: Size: XL, Size: M, kind:refactor

#1295 feat: Operation information of nodes is collected and reported to the Placement Center
  src/cmd/src/placement-center/server.rs
  src/mqtt-broker/src/broker.rs
  src/mqtt-broker/src/handler/heartbeat.rs
  src/mqtt-broker/src/handler/heatbeat.rs
  src/placement-center/src/controller/journal/gc.rs
  src/placement-center/src/controller/journal/mod.rs
  src/placement-center/src/controller/mqtt/connector/scheduler.rs
  src/placement-center/src/controller/mqtt/connector/status.rs
  src/placement-center/src/controller/mqtt/session_expire.rs
  src/placement-center/src/core/cache.rs
  src/placement-center/src/core/cluster.rs
  src/placement-center/src/core/controller.rs
  src/placement-center/src/core/heartbeat.rs
  src/placement-center/src/core/schema.rs
  src/placement-center/src/lib.rs
  src/placement-center/src/raft/leadership.rs
  src/placement-center/src/raft/raft_node.rs
  src/placement-center/src/raft/route/apply.rs
  src/placement-center/src/server/grpc_server.rs
  src/placement-center/src/server/mod.rs
  src/placement-center/src/server/service_inner.rs
  src/placement-center/src/server/service_journal.rs
  src/placement-center/src/server/service_kv.rs
  src/placement-center/src/server/service_mqtt.rs
  src/placement-center/src/server/service_raft.rs
  src/placement-center/src/server/services/inner.rs
  src/placement-center/src/server/services/journal/segment.rs
  src/placement-center/src/server/services/journal/shard.rs
  src/placement-center/src/server/services/kv.rs
  src/placement-center/src/server/services/mqtt/acl.rs
  src/placement-center/src/server/services/mqtt/connector.rs
  src/placement-center/src/server/services/mqtt/session.rs
  src/placement-center/src/server/services/mqtt/subscribe.rs
  src/placement-center/src/server/services/mqtt/topic.rs
  src/placement-center/src/server/services/mqtt/user.rs
Labels: kind:feat, Size: M, Size: L

#1303 style: Resolve style inconsistencies in the command-line interface
  src/cmd/src/cli-command/mqtt/admin.rs
Labels: Size: S, kind:style

#1308 style:fix schema style
  src/cmd/src/cli-command/command.rs
  src/cmd/src/cli-command/mqtt/admin.rs
Labels: Size: M, kind:style

#1310 refactor: Reduce excessive function parameters in follower.rs
  src/mqtt-broker/src/subscribe/share/follower.rs
Labels: Size: M, kind:refactor

#1311 fix: fixing inconsistent connections
  src/mqtt-broker/src/server/tcp/v1/tcp_acceptor.rs
Labels: kind:bug, Size: S

#1316 build(rdkafka): Use rdkafka's CMake to solve the compilation issues on Windows.
  Cargo.lock
  Cargo.toml
Labels: size/xs, kind:build
